### ISSUE TITLE
rofi (dmenu replacement)

### ISSUE THREAD

**Issue by from-nibly** [clearlinux/distribution#1010]
git repo here: https://github.com/davatorium/rofi
installation instructions here: https://github.com/davatorium/rofi/blob/next/INSTALL.md

Using the [meson release instructions](https://github.com/davatorium/rofi/blob/next/INSTALL.md#meson) I install the missing packages up till it needs 'xcb-xrb'.  If I `swupd search xcb-xrb` I get nothing. If I `swupd search xcb-util-xrb` I find I can install it through `desktop-awesome` which I already have installed. For whatever reason meson (and the auto tools install) cant find the xcb-xrb library.

Wondering if I could get some help compiling this and turning it into a package/bundle. Rofi is great and a permanent part of my personal workflow. Right now I just compiled it in a debian docker container and yanked the binary out through a mount. (looks like it's either statically compiled or I have all the required libs installed).

I am kind of a noob when it comes to compiling stuff on linux c++/c style, but I am definitely willing to help turn this into a package if I can get pointed in the right direction on debugging the compile issue and pointed at some docks on how to create the package.

**Comment by bryteise** [comment]
So I can likely get this in a bundle for you. That said, I'd like to try and help with your broader question about building content for Clear Linux. Please take a look at our [common](https://github.com/clearlinux/common) package for documentation on how to build things using Clear Linux's [autospec](https://github.com/clearlinux/autospec/) tool. Once you have setup your environment you should be able to get rofi to build and you'll have an rpm that can be either locally installed or you can submit a patch for what autospec configuration options you needed to make so that we can easily replicate your build and integrate the package into Clear Linux.

**Comment by from-nibly** [comment]
Awesome. I'll take a look at it and I will let you know what I find.

**Comment by curantes** [comment]
Maybe close this since rofi was added by @ahkok back at 2019-07-30 to desktop-i3 bundle
