### ISSUE TITLE
[Package Request] Commonly used i3 apps

### ISSUE THREAD

**Issue by nsgnn** [clearlinux/distribution#1011]
I have recently swapped to i3 and needed to look about how most people use it. On the way, I discovered a few nearly universally used tools. I propose the addition of a common `desktop-i3-apps` bundle to include commonly used tools within i3. The list I can think of would be the following:

- [ARandR](https://gitlab.com/arandr/arandr)
  - This allows for GUI control over connected displays. It relies on XRandR which is already found within the x11 tools bundle.
- [i3blocks](https://github.com/vivien/i3blocks)
  - A widely used alternative to the default i3status. It would be rather light clutter if not used actively.
- [Compton](https://github.com/yshui/compton/releases/tag/v6.2)
  - Compositor that would allow for screen tearing to be fixed. It has a more recent release, but this was the most recent full release. 
  - Also seen here: #984 
- rxvt-unicode
  - Already included within the `desktop-apps-extra` bundle. Could be broken into it's own bundle and also included within the proposed bundle as well.
- [rofi](https://github.com/davatorium/rofi)
  - It would be a good addition to this bundle. The user can config i3 to open dmenu or rofi. 
  - This was brought up in issue #1010 as well. 

These are all rather lightweight and out of the way inclusions. Such that if not all apps are in use, they are not in the way or large enough to cause strife over the file sizes.

**Comment by fenrus75** [comment]
looks reasonable to me; we'll poke at these

**Comment by ahkok** [comment]
`arandr` is a separate bundle. Added it a week back or so, I think.
`i3blocks` will be part of the `desktop-i3` bundle, added in a day or so.
`compton` doesn't seem to be ready for prime time yet - uses submodules, recently forked from an abandoned project.... in any case I couldn't build it just yet.
`rxvt-unicode` was recently added as a separate bundle, too.
`rofi` will be added to the `desktop-i3` bundle in a day or so.

Because that closes on 4/5, and there is a separate issue for compton, we can close this issue!
