### ISSUE TITLE
Missing symbol in python3

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/distribution#1068]
Starting with Clear Linux* OS release 30480, get an undefined symbol for python3 when running my Vim plugin:
ImportError: /usr/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so.avx2: undefined symbol: PyByteArray_Type

This can reproduce by just importing struct in Vim:
Launch `vim`
In Vim execute: `:py3 import struct`

Likely the bug was introduced in release 30470.

Reverting back to release 30450 the problem goes away.

This is preventing the use of my development plugin YouCompleteMe and impacting my productivity.

**Comment by phmccarty** [comment]
In build 30470, the python3 package was modified to additionally install the libpython3.7m.a static library. Afterward, vim was upgraded and began linking with this static library, because `/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/` is python's "config" location and ` /usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a` and available to use.

I think we want vim to link with the shared library instead, but I doubt we could easily manage this unless we fix the build of the python3 package.

As for the `ImportError` you are running to, I suspect [this patch](https://github.com/clearlinux-pkgs/python3/blob/bb28d895b89a55746c6ffae41356947b49192adb/0004-Add-avx2-and-avx512-support.patch) may be to blame, which I would not expect to work with projects are built against the static libpython3.

**Comment by phmccarty** [comment]
@mrkz The static library under `/usr/lib/python3.7/...`, so I'll add that to -staticdev as well. Then the workaround will be good enough for now.

**Comment by phmccarty** [comment]
Fix in progress.

The other libpython3 static library has been moved to `python3-staticdev` as well, and I just rebuilt vim/gvim to fix the issue @mdhorn reported.

**Comment by mdhorn** [comment]
Thanks @phmccarty !  Confirmed fixed in 30620
