### ISSUE TITLE
Please update `atom` to 1.39.1

### ISSUE THREAD

**Issue by zraffer** [clearlinux/distribution#1089]
The distribution version is 1.37, it's two major releases below upstream
https://github.com/atom/atom/releases/tag/v1.39.1

**Comment by Jacalz** [comment]
Actually we have 1.40.1 available so I would recommend updating to that version instead :+1:

**Comment by Jacalz** [comment]
Pinging @fenrus75 for this as he seems to be maintaining the package...

**Comment by bryteise** [comment]
My comment isn't especially a happy one because packaging atom is currently done in a way the Clear Linux team doesn't like and it is a difficult thing (as most electron apps are) to do well. It is likely we move atom out of the official distro and into our 3rd-party content repos (so still maintained and shipped by us but using a different build and deployment flow) and that is when it will definitely be updated. Not to say we won't do it before but it is behind other work unfortunately.

**Comment by Jacalz** [comment]
That's sad to hear but could it possible just be updated one before then though? The current version is broken and can't remove files which is quite annoying an the flatpak version doesn't work with go-plus :(

**Comment by zraffer** [comment]
I can confirm that the flatpak version cannot work with any development
tools which is not in container. AFAIK any Flatpak applications can run
external executables but cannot use external libraries, that is the
problem. As a workaround personally me is using the tar-zipped distribution
of `atom` like
https://github.com/atom/atom/releases/download/v1.41.0-beta1/atom-amd64.tar.gz

**Comment by bryteise** [comment]
I would probably recommend using the release mentioned by @zraffer but I have updated the package in Clear to 1.40.1.
