### ISSUE TITLE
nginx-mainline PageSpeed Module ngx_pagespeed

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1137]
Running a LEMP Stack on Clear Linux
nginx-mainline
MariaDB
PHP-Basics

I've love to have ngx_pagespeed module to be easily install perhaps as a bundle
https://github.com/apache/incubator-pagespeed-ngx

Alternatively, bundle featuring 3rd party nginx modules: 
nxinx-mainline-extras
https://www.nginx.com/resources/wiki/modules/

Regards

**Comment by ahkok** [comment]
So, I'd be happy to support this and perhaps a bunch more nginx addons. I think we'll do this for nginx-mainline only though - just to prevent further conflicts with the old version of nginx.

**Comment by ketonik** [comment]
Some standout valuable modules from that list:
ngx_brotli for asset compression
ngx_redis2
ngx_http_enhanced_memcached_module
memc-nginx-module
ngx_http_php_memcache_standard_balancer
nginx_cookie_flag_module, (support)
ngx_http_secure_download
nginx-sflow-module https://github.com/sflow/nginx-sflow-module
nginx-video-thumbextractor-module

Here's another list of modules:
https://github.com/agile6v/awesome-nginx

any updates?

**Comment by ahkok** [comment]
Yeah, we really need to get this done

**Comment by ketonik** [comment]
Varnish-cache bundle was removed without warning or reason (at least i didn't find any info) any idea what the situation with that is?

Nuster, HTTP proxy cache server and RESTful NoSQL cache server

maybe of interest in LEMP stacks on Clear Linux 

https://github.com/jiangwenyuan/nuster

**Interesting performance related benchmarks:**
Web cache server HTTP 2 performance benchmark: nuster vs nginx
https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-HTTP-2-performance-benchmark%3A-nuster-vs-nginx

**Performance benchmark: nuster vs nginx vs varnish:**
https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark%3A-nuster-vs-nginx-vs-varnish-vs-squid

**Web cache server performance benchmark: nuster vs squid:**
https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark%3A-nuster-vs-squid

**Comment by ahkok** [comment]
> Varnish-cache bundle was removed without warning or reason (at least i didn't find any info) any idea what the situation with that is?

I don't know what this is about, sorry. We've never had this package?

**Comment by ahkok** [comment]
So, while looking at how to do this in a structurally nice way, I can see that it's going to be painful.

From what it appears like, all the nginx modules need to be compiled with the nginx source code available.

This means that we need to stick all of these into the `nginx-mainline` package, and build them all together.

Alternatively, every single nginx module needs to include a copy of the whole nginx-mainline package.

Ouch

I'm not a big fan of this. This is not sub-optimal. It is terrible.

**Comment by ketonik** [comment]
> > Varnish-cache bundle was removed without warning or reason (at least i didn't find any info) any idea what the situation with that is?
> 
> I don't know what this is about, sorry. We've never had this package?

It's been in many releases, here's one:
https://cdn.download.clearlinux.org/releases/30960/clear/source/SRPMS/

**Comment by ketonik** [comment]
nginx source is very tiny, bundling it to every module source is no problem and not terrible at all.

I **highly** doubt there will be any **usable** movement of their packaging in months to come.

nginx badly needs brotli compression support to compress server assets, css, js, html files etc.

Currently we really have only a barebones nginx solution here on this Clear Linux OS.

**Comment by ahkok** [comment]
Not needed.

I've created a `devel` package for `nginx-mainline` which allows us to compile dynamic modules separately without duplicating all the sources. This allows us to use `autospec` and pretty much press a button to import these modules. All the hard work is taken out of the equation and there only will be one copy of the nginx headers to compile against. (ref: https://github.com/clearlinux/autospec/pull/483)

I've tested this with the `ngx_http_auth_pam_module` package since I needed a simple one to start with that didn't have any missign dependencies. Now, I still have to *validate* that it works, but it should reasonably be that if it compiles OK, it will just load, since it's just a simple DSO.

I can therefore now in the next week look at the above items and make an `nginx-mainline-extras` bundle where these modules will end up living.

So, this is major progress, and you'll soon be able to try it out.

**Comment by ketonik** [comment]
big news, wickid, hanging out for next week, thanks for update.

**Comment by ahkok** [comment]
> I've love to have ngx_pagespeed module to be easily install perhaps as a bundle

I've kept this for last, but, wow, the instructions for this are a trainwreck.

**Comment by ketonik** [comment]
How's the progress mate?
All be available ready for us to implement on our nginx-mainline server by end of week?

**Comment by ahkok** [comment]
Update since this has been open for a while now:

- loading modules is now tested in nginx-mainline/nginx-mainline-extras
- several nginx modules are now added (See: https://github.com/clearlinux/clr-bundles/blob/master/bundles/nginx-mainline-extras)
- still not added: `ngx_pagespeed` due to it's complexity

**Comment by ketonik** [comment]
Nice, so is ready now to install?

**Comment by ahkok** [comment]
I'm rejecting `ngx_pagespeed`. All the other stuff is 100% ready to install since last week.

`ngx_pagespeed` is too complex and time intensive for me to package properly. The instructions and build scripts are **horrendous** and software like that **should not be made public unless you want to embarrass yourself**.

Whoever wrote this project does clearly not want it to be used.

I'll take patches, though, if someone actually understands their build instructions and makes a package that meets our packaging guidelines.

**Comment by ahkok** [comment]
@dvershinin I'd love to see an improvement, but seeing folders like this really puts me off:

https://github.com/apache/incubator-pagespeed-mod/tree/master/install

**Comment by dvershinin** [comment]
@ahkok they are indeed a mess and PSOL (PageSpeed Optimization Libraries) have to be compiled separately and/or having to use binary distribution for the same static library (which itself is built-in with a bunch of libraries instead of being dependent on the system ones).

Instructions to compile PSOL from source are very sparse, they have been changing "build systems" to complicate the matters (old instructions do not work).

If you went with relatively straightforward way of using binary static PSOL (that they provide for download) and compile ngx_pagespeed with it, this can be done, but I'm just not sure how this magical `autospec` works.

Is it not possible to build stuff in Clearlinux *from existing `.spec` files*? If someone told me it's possible, I would be sure to look at it.

**Comment by ahkok** [comment]
Our build system cannot download external sources, which is one complicating factor. Everything has to be present at the start of the build.

Second, we have a requirement that everything must be built from source.

Honestly, I don't even know for sure whether this is actually the correct URL to get PSOL from, since official instructions are to download a binary version from dl.googlecode.com.

-> https://github.com/apache/incubator-pagespeed-mod/archive/v1.13.35.2.tar.gz

It'd be lovely if you can at least confirm that that actually is the right thing to start. We can build static binary archives of course, it doesn't need to be dynamic.

I usually don't give up quickly...

**Comment by dvershinin** [comment]
> Our build system cannot download external sources, which is one complicating factor. Everything has to be present at the start of the build.

This should not be a problem if you treat the binary PSOL as once of the `Source`s. Assuming you have to download source anyway, you will get the PSOL as well, before the build begins, not during it.

> Honestly, I don't even know for sure whether this is actually the correct URL to get PSOL from, since official instructions are to download a binary version from dl.googlecode.com

You would want to look at the latest release tag of ngx_pagespeed and check [this file](https://github.com/apache/incubator-pagespeed-ngx/blob/v1.13.35.2-stable/PSOL_BINARY_URL).

With every new release of ngx_pagespeed, this file is updated with the link to corresponding static PSOL binaries.

That's as far as building with static library (which isn't perfect, but a working scenario)...

> Second, we have a requirement that everything must be built from source.

Not much luck there. If you just download regular PSOL sources, you have to "prepare it" and run through quite a bunch of things including Google `gyp` stuff, etc, where main trouble is fetching *all* dependency libraries, which are not there in source releases of PSOL. 

To say that there are few required libraries is to [say nothing](https://github.com/apache/incubator-pagespeed-mod/blob/master/.gitmodules).

To bring things closer to sanity, you can get "prepared" source tarballs from [this ticket](https://github.com/apache/incubator-pagespeed-mod/issues/968) - for every source release, they publish tarballs there which include dependency libraries. This makes things a bit easier, but only so for a moment - you can see my last comment in there, I was almost near to success with those, haha.

I was only successful in building PSOL from source when using *un*prepared source archives, and going through all the painful fetching of all dependency libraries using those Google downloading stuff (and those often linked with https:// as opposed to git for submodules, made it even unreliable). So eventually it was trying and trying and I succeeded only once without a clean track of "how the heck did it finally download and compile"? :-D

**Comment by ketonik** [comment]
Can I make a request for another nginx module please?
I need to geoblack specific countries from accessing my server.

Module ngx_http_geoip_module
http://nginx.org/en/docs/http/ngx_http_geoip_module.html
