### ISSUE TITLE
Optimizations above -O1 causing multiple 32bit applications to stop working (e.g. Civilization 5)

### ISSUE THREAD

**Issue by LeonSkoog** [clearlinux/distribution#1152]
Hi, 
I'm seeing the same issues as reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1471427 
https://bugs.gentoo.org/616402 

Basically multiple 32bit applications are crashing. 
Looks like the solution would be to add '-mstackrealign' compilation option for 32bit packages in clear linux repo.

**Comment by thiagomacieira** [comment]
That option is a workaround against buggy, old code. The ABI for Linux changed some 15 years ago to require stacks to be aligned to 16 bytes.

The applications crashing are at fault, not Clear and not the libraries that are crashing.

**Comment by thiagomacieira** [comment]
Since Clear only supplies 32-bit libraries for compatibility with old games, I support adding the workaround of forcing the stack realignment in all 32-bit code. Kind of pointless to have those libraries but them not work for the few programs that use them. Or, like was suggested in the Red Hat issue, drop all SSE optimisations from 32-bit code and run with "bare i686".

32-bit code is not performance sensitive. Making it even slower is acceptable.

**Comment by sunnyflunk** [comment]
The two main culprits for this are the 32bit versions of `openal-soft` and `glibc`. Fixing those 2 tends to prevent the crashes that result in other libs.

I'm not sure what the performance hit is from using `-mstackrealign`, but from my perspective (someone playing 32bit games on integrated intel gfx), the only part where performance actually makes a real difference are the graphics drivers (so mesa and potentially llvm once iris becomes default). I certainly notice 32bit games are much more performant on CL.

**Comment by thiagomacieira** [comment]
Any and all libraries that those games link to could cause this issue. This is more so the case in Clear than in other distros because we do compile with `-march=westmere` even on 32-bit, while other distros don't. Therefore, if we're going to do this, then we should make the changes to all 32-bit packages.

As for the game itself, if it was compiled sometime in the early 2000s, performance of todays CPUs and GPUs should be sufficient to make it run smoothly. If requires better performance, then one would expect that those games to have been recompiled sometime in the last 10 years, which means they shouldn't be misaligning the stack.

[Unless they are sharing binary code between Windows and Linux, but compiling on Windows]

**Comment by ahkok** [comment]
> 32-bit code is not performance sensitive. Making it even slower is acceptable.

agreed

**Comment by LeonSkoog** [comment]
> The applications crashing are at fault, not Clear and not the libraries that are crashing.

@thiagomacieira - Yep, I agree. The problem is that the faulty applications may never be updated. 
So the users can't do anything about it, we need help from the Linux distribution side :)

**Comment by thiagomacieira** [comment]
So we're in agreement.

We'll add `-mstackrealign` to the 32-bit CFLAGS so those libraries get the option as they're recompiled.

That won't affect assembly source. I think only glibc has those that is relevant.

**Comment by LeonSkoog** [comment]
> We'll add `-mstackrealign` to the 32-bit CFLAGS so those libraries get the option as they're recompiled.

@thiagomacieira Great news, thanks!
Do you have any ETA for this?

**Comment by sunnyflunk** [comment]
Can you ask for openal-soft and pulseaudio to be rebuilt also?

I've tested both an Unreal Development Kit game and an Aspyr Media port (which are the most common games showing these 32bit crashes) and are both fixed after rebuilding these packages with `-mstackrealign`.

**Comment by LeonSkoog** [comment]
@thiagomacieira  - any update?

**Comment by thiagomacieira** [comment]
I sent for internal review the glibc update. Autospec's matching change is at https://github.com/clearlinux/autospec/pull/460

**Comment by thiagomacieira** [comment]
Autospec was approved, glibc, openal-soft and pulseaudio are rebuilt and will be in the next build. Thanks for being patient.
