### ISSUE TITLE
Document for hybrid graphics (intel-nvidia)

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1164]
Hi clearlinux team:

My laptop has two graphics intel, nvidia. How can I get them worked with clearlinux? Followed the tutorial for nvidia graphic card. But it didn't work for my laptop.

**Comment by Darklink999999** [comment]
> Hi clearlinux team:
> 
> My laptop has two graphics intel, nvidia. How can I get them worked with clearlinux? Followed the tutorial for nvidia graphic card. But it didn't work for my laptop.

Hello :D

1. You have to follow the tutorial found in the Clear Linux page.
2. If the computer doesn't boot use a terminal (ALT+CTRL+F2 or F3 etc. on the error page or the blank screen). Another solution is to boot from the Live USB and open a terminal there in the necessary folder on your hard drive (the Live USB will have it in "Other Locations"). You have to follow [this](https://medium.com/@vfbsilva/howto-set-up-prime-with-nvidia-proprietary-driver-c647e3597447) guide (ignore sections 1 and 2 as they're for Manjaro users) but in section 3.1 instead of the text it mentions follow [this](https://download.nvidia.com/XFree86/Linux-x86_64/396.51/README/randr14.html) page.
3. You should be done but if the computer hangs on the boot screen check `var/log/Xorg.0.log`. If the problem is that the it doesn't load both ModulePaths (namely `/opt/nvidia/lib64` and `/usr/lib64/xorg/`) copy the nvidia modules from `/opt/nvidia/lib64` to `/usr/lib64/xorg/modules` using the Live USB (you will need to use the path `/run/media/clrlinux/`). If you need any more help let me know.

**Comment by stokhos** [comment]
@lebensterben @Darklink999999 Cool I will try to do this over weekend. Thanks guys.

**Comment by Darklink999999** [comment]
> @lebensterben @Darklink999999 Cool I will try to do this over weekend. Thanks guys.

Ok, all the .conf files needed for a successful installation are in [this](https://community.clearlinux.org/t/configuration-files-for-nvidia-drivers-on-optimus-laptops/1464) thread. If something goes awry just boot from the Live USB and copy-paste the files from **this** thread (I just linked). The post @lebensterben posted contains two wrong lines and things won't work if you copy from there (if you read the whole thread you'll see which lines I'm talking about). If you need anything else just reply here and also post the log from `/var/log/Xorg.0./log`. :smile:

**Comment by stokhos** [comment]
@Darklink999999  I followed instructions in your link. But my laptop freezes with "iwlwifi 0000:04:00.0: BIOS contains WGDS but no WRDS" on my screen. Can't login. What should I do?

**Comment by Darklink999999** [comment]
> @Darklink999999 I followed instructions in your link. But my laptop freezes with "iwlwifi 0000:04:00.0: BIOS contains WGDS but no WRDS" on my screen. Can't login. What should I do?

Wth? This is a wifi error, it should have to do with anything in the .conf files I posted. What are the exact steps you followed?

**Comment by stokhos** [comment]
@Darklink999999 I dont know, I guess it stops before GDM starts. I followed the instruction in that link. I mean I manually created those files. And I installed the nvidia with the commend from [https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#download-and-install-the-nvidia-drivers](url)

**Comment by Darklink999999** [comment]
> @Darklink999999 I dont know, I guess it stops before GDM starts. I followed the instruction in that link. I mean I manually created those files. And I installed the nvidia with the commend from [https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#download-and-install-the-nvidia-drivers](url)

Your problem is a WiFi one which doesn't make any sense as the Nvidia Graphics Drivers don't have anything to do with it. Also the procedure you followed was incorrect. 
1. Remove all the config files you created. Does that fix your problem? Can you at least get to a terminal using CTRL+ALT+F3?
2. Follow the tutorial. Or if you're bored just execute the scripts of [this](https://community.clearlinux.org/t/bash-scripts-to-automate-installation-of-nvidia-proprietary-driver/368) thread.
3. **Follow the [guide](https://medium.com/@vfbsilva/howto-set-up-prime-with-nvidia-proprietary-driver-c647e3597447) for Nvidia Prime.**
4. **If things don't work**, copy and paste the config files I provided at the specified locations. **This is the last step and it's optional**.

**Comment by Darklink999999** [comment]
Ok  I tried the procedure myself, it doesn't work and I get a black screen too, I'll ask in the forums and let you know how it goes. :D

**Comment by lebensterben** [comment]
> @Darklink999999 I dont know, I guess it stops before GDM starts. I followed the instruction in that link. I mean I manually created those files. And I installed the nvidia with the commend from [https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#download-and-install-the-nvidia-drivers](url)

Can you open a new issue for the error "iwlwifi 0000:04:00.0: BIOS contains WGDS but no WRDS"

**Comment by lebensterben** [comment]
Similar problems had been reported on Manjoro's forum [here](https://forum.manjaro.org/t/solved-hdmi-problems-with-hardwired-nvidia-gpu/85443/4), but it doesn't seem to be resolved.

**Comment by jiblime** [comment]
I've been getting keyboard lockups in TTY, using Alt + Sysrq + R unlocks my keyboard if Xorg fails to start.

I've set up Nvidia Optimus through a different distro's package manager, although I've had to setup my ~/.xinitrc, /etc/X11/xorg.conf and /etc/X11/xorg.conf.d/* files. The guides I followed can be seen here:

https://download.nvidia.com/XFree86/Linux-x86_64/435.21/README/randr14.html
https://wiki.gentoo.org/wiki/NVIDIA/Optimus

So far I've been able to get into a crashed Plasma desktop. I copied the files I had and edited them to match the new library locations, but I need some help figuring out which files are being clobbered that I need to save. 

`sudo swupd repair --quick --bundles=lib-opengl` returns `repair: unrecognized option '--bundles=lib-opengl'`, so I went with `sudo swupd repair -q` instead, which, as the guide says, shouldn't be used. This also does not work.

**Comment by lf-araujo** [comment]
Hi @jiblime can you confirm the solution on your previous answer still works? Avoiding GDM/lightdm solves the problem?

Thanks

**Comment by migueldevmt** [comment]
> > Hi clearlinux team:
> > My laptop has two graphics intel, nvidia. How can I get them worked with clearlinux? Followed the tutorial for nvidia graphic card. But it didn't work for my laptop.
> 
> Hello :D
> 
> 1. You have to follow the tutorial found in the Clear Linux page.
> 2. If the computer doesn't boot use a terminal (ALT+CTRL+F2 or F3 etc. on the error page or the blank screen). Another solution is to boot from the Live USB and open a terminal there in the necessary folder on your hard drive (the Live USB will have it in "Other Locations"). You have to follow [this](https://medium.com/@vfbsilva/howto-set-up-prime-with-nvidia-proprietary-driver-c647e3597447) guide (ignore sections 1 and 2 as they're for Manjaro users) but in section 3.1 instead of the text it mentions follow [this](https://download.nvidia.com/XFree86/Linux-x86_64/396.51/README/randr14.html) page.
> 3. You should be done but if the computer hangs on the boot screen check `var/log/Xorg.0.log`. If the problem is that the it doesn't load both ModulePaths (namely `/opt/nvidia/lib64` and `/usr/lib64/xorg/`) copy the nvidia modules from `/opt/nvidia/lib64` to `/usr/lib64/xorg/modules` using the Live USB (you will need to use the path `/run/media/clrlinux/`). If you need any more help let me know.
> 
> PS. DO NOT RUN nvidia-xconfig or nvidia-settings if things don't work.

(i don't speak english very well but i want to answer to help other people too) 1. i just run the [scripts](https://community.clearlinux.org/t/bash-scripts-to-automate-installation-of-nvidia-proprietary-driver/368) and then follow the step 2 and it worked :DD, after reboot, everything went fine.

**Comment by mirkokirchner** [comment]
> 

it worx
