### ISSUE TITLE
iwd - iNet wireless daemon

### ISSUE THREAD

**Issue by Kokokokoka** [clearlinux/distribution#1196]
Please, consider adding iwd/iwctl as a wpa_supplicant replacement.

**Comment by ahkok** [comment]
We've definitely considered it before and still are. One of the major issues is how to resolve conflicts with dependencies. It's not entirely as simple as just dropping `iwd` on a system by itself.

**Comment by jprestwo** [comment]
@ahkok could you elaborate on what this "conflicts with dependencies" issue is? Is there something the IWD project itself could do to resolve this?

**Comment by ahkok** [comment]
For instance, how do we make sure that NetworkManager doesn't use iwd by default, even when it is installed, but there is a simple way to enable it for users.

**Comment by ahkok** [comment]
Obviously it may not break NM if it's not installed either. NM must remain working when iwd is uninstalled.

I'd also like to see if `systemd-networkd` could use `iwd` somehow.

**Comment by jprestwo** [comment]
NetworkManager requires you enable IWD as the backend via the config file. So it would be up to the user to turn this on if they installed the IWD package (unless clear can do this somehow automatically, idk). Since this is the case, the 'default' NM installation would always choose wpa_s unless clear modified the config file.

And AFAIK sysetmd-networkd is fully compatible with IWD.

**Comment by thiagomacieira** [comment]
systemd-networkd and iwd/wpa-supplicant are complementary, though it would be really nice if iwd integrated better with systemd than wpa-supplicant does.

**Comment by ahkok** [comment]
I'm making this a separate bundle - `iwd`. We'll have to experiment with it to see if it's properly working but I would like to see if this behaves nicely together with `systemd-networkd` as well.

**Comment by ahkok** [comment]
Should be available in 1-2 days.
