### ISSUE TITLE
Mouse not working using VMware Workstation over RDC

### ISSUE THREAD

**Issue by ghost** [clearlinux/distribution#1203]
Hello,

I run a dedicated Windows 2019 server in a datacenter and connect to it with RDC. The server runs VMware Workstation with various VMs. The issue with CL is the same as with FreeBSD, the mouse only moves along the sides of the VM environment. The same VM instance worked just fine when I used it on my notebook (same with Windows 2019 and VMware Workstation 15.1 on the notebook).

The funny thing is that with Debian 10 and Gnome 3, it just works fine, no issues on 6 Debian VM's. 

On CL the VMware tools are installed this way:

sudo
swupd bundle-add os-cloudguest-vmware-gui
systemctl enable open-vm-tools
reboot

**Comment by puneetse** [comment]
The latency between a local notebook and a remote connection is going to have an impact. Do you have VMs on the same remote host that are behaving differently?

Mouse emulation (RDC) over mouse emulation (VM) is also sketchy in my experience anyways. Can you connect to the VM directly instead (e.g. VNC, SSH)? 

> The issue with CL is the same as with FreeBSD, the mouse only moves along the sides of the VM environment.

The you please explain what this means in more detail? Is it that the mouse gets "captured" in the VM console window and you have to hi CTRL+ALT to release it?

**Comment by Pummelchen** [comment]
Hello,

latency is no issue as otherwise all Windows and Debian VM's would be affected, too, which is not the case. I'm on 200MBit fiber connection in the home and the RDC sessions are very quick and responsive.

I could connect to each VM via the VNC server feature of VMware Workstation, but that would be a workaround, not a fix.

In CL and FreeBSD the mouse cursor is visible on the GNOME desktop. However when I try to move the mouse, using my Logitech mouse, the touchpad from my notebook or via the red dot joystick (Lenovo notebook), than no matter how I move the mouse, it just slides along the outside borders of the screen. You cannot move the cursor into the center of the screen to click on something.

On CL and FreeBSD I installed the VMware tools as advised, but its not working. Works just find on all Debian and Windows VM's.

**Comment by puneetse** [comment]
Thanks for clarifying the issue @Pummelchen

**Comment by nesiusra** [comment]
@puneetse - I'll connect you with someone who can hopefully help you reproduce this internally.

**Comment by puneetse** [comment]
Sounds good, thanks.

**Comment by puneetse** [comment]
@Pummelchen if you're still out there, check out this thread on the forums related to your reported issue. https://community.clearlinux.org/t/must-use-ctrl-alt-to-free-mouse-from-vmware-console/1853/16

Updating to 31330+ and bumping up video memory should help a lot.
