### ISSUE TITLE
why is Clear Linux OS release is distributed as .xz instead of .iso

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1239]
Now i need to know that i have to download and install 7z unzip in windows 10 and make that .iso work.

![image](https://user-images.githubusercontent.com/12841320/65007131-e5440100-d924-11e9-88e8-cac10f7acbda.png)

**Comment by mdhorn** [comment]
Reviewed other distros and *none* of the following compress their ISO images:

- Arch Linux
- CentOS
- Debian
- Fedora
- Linux Mint
- openSUSE
- OracleLinux
- ubuntu

We should probably consider not compressing our ISOs for Clear Linux* OS too.

**Comment by puneetse** [comment]
This would also reduce documentation complexity a little and avoid people accidentally dd'ing the compressed archive instead of the extracted iso...not that I've ever done that :)

**Comment by fenrus75** [comment]
or we do both; xz for those with server like setups and maybe weak bandwidth
and uncompressed for people who have bandwidth and don't want the extra step

it's the same content just differently wrapped

**Comment by thiagomacieira** [comment]
> This would also reduce documentation complexity a little and avoid people accidentally dd'ing the compressed archive instead of the extracted iso...not that I've ever done that :)

Or people who use `curl | unxz | dd` pipeline and then don't notice that the download failed because the server timed the connection out while dd was writing multiple megabytes of zero originating from a 1k block of xz data... I once spent over a day with bad images until I realised that.

Another use is that some Cloud providers accept image URLs, but only uncompressed. Installing Clear involves downloading the image, uncompressing it, then uploading back to the provider. On a 15 Mbit/s Comcast upstream, a 6 GB image takes over an hour to upload.

**Comment by mdhorn** [comment]
The ISOs are already compressed using squashfs, so the xz version is likely not much smaller.

**Comment by ahkok** [comment]
The last time I checked, it uncompressed the 2.4gb iso.xz to a 2.4gb iso.

and XZ uncompression is slow.

**Comment by nazar2sfive** [comment]
yes it is slow and unnecessary for the end user. takes time.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/66018056-3cd59580-e4fd-11e9-9d94-9a6a5aee9f1a.png)

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/66269965-5c0e5300-e86e-11e9-897d-838c05811dfe.png)

clear linux docs wants it to be used as iso then.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/66822359-d5d7c800-ef63-11e9-87ce-0ddcd8135722.png)

Thanks
