### ISSUE TITLE
Complete the Sway experience: Swaybg, Swayidle, Swaylock, Alacritty, Waybar, Brigtnessctl

### ISSUE THREAD

**Issue by libXq** [clearlinux/distribution#1296]
I would love to see Alacritty and Waybar coming to the Clear Linux repository. Alacritty is very popular by Sway users (my absolute favorite terminal emulator). Waybar is a really nice addition to complete Sway as well. Swaylock and Swayidle are also missing. And brigntessctl is an overall nice little software to adjust screen brightness with user udev rules (great in addition to sway and waybar (shortcut, bar-icon-element)). Swaybg is also missing. IMHO Sway is pretty incomplete in the Clear Linux repos. I would compile those myself but I am not a dev. I am just a Arch Linux user loving tilling window managers. 

By adding those packages Sway could be a suitable alternative to Gnome/Mutter and KDE/KWIN in ClearLinux! The one and only tilling window manager based on Wayland (no tearing tilling :D). In the current stat the swupd bundle sway is a little useless at least for me. https://clearlinux.org/software/bundle/sway

I suggest the following bundles.

sway  - sway, swaybg
sway-additions - "swayidle, swaylock" or "swayidle and swaylock as separate bundles"
waybar - just waybar and dependencies 
alacritty - just alacritty and dependencies
alacritty-terminfo - terminfo files for alacritty
brightnessctl - just brightnessctl

How Arch ships Sway:
https://www.archlinux.org/packages/community/x86_64/sway/ -swaybg is a dependency
https://www.archlinux.org/packages/community/x86_64/swayidle/ -optional to sway
https://www.archlinux.org/packages/community/x86_64/swaylock/ -optional to sway

urls:
sway: https://github.com/swaywm/sway
swaybg: https://github.com/swaywm/swaybg
swayidle: https://github.com/swaywm/swayidle
swaylock: https://github.com/swaywm/swaylock
waybar: https://github.com/Alexays/Waybar/
brightnessctl: https://github.com/Hummer12007/brightnessctl

**Comment by ahkok** [comment]
Why would this all be split up into separate bundles? These are all relatively small packages.

**Comment by ahkok** [comment]
Sway is already added, please remove it from your list.

**Comment by GitHubRepositoryX** [comment]
> Why would this all be split up into separate bundles? These are all relatively small packages.
Because of the molecularity of sway itself. Those are optional packages.


> Sway is already added, please remove it from your list.

I added it into the list of an example, how I would do the packages. There is also a dependency issue with the current sway bundle. https://github.com/clearlinux/distribution/issues/1295

**Comment by MattiaVerticchio** [comment]
I agree with @ahkok on this, those are commonly used packages with Sway. It could be more practical to bundle some of them into a single `sway` bundle.

A good `sway` bundle in my opinion would include `swaybg`, `swayidle`, `swaylock` and `waybar`.

`alacritty` and `alacritty-terminfo` could be packaged together into a single `alacritty` bundle.

About `brightnessctl`, it could fit into the `sway` since it's commonly used too. I actually prefer `brillo`, since it uses a natural exponential function for controlling backlight, and has smooth transitions. But this a matter of personal taste.

**Comment by ahkok** [comment]
I've spent some time setting up a "minimal" system with `lightdm` and `sway`, but, it seems `/usr/bin/sway` by itself does not like to be run directly under `lightdm`.

I don't really want to go digging into `gdm` since I think very few people are going to be interested in it. It appears that there's some major disconnect where `lightdm` should end and `sway` should pick up, but I can't just yet figure it out. `sway` just dies and gives up.

**Comment by steven-gg** [comment]
Well, if this is done the very next day I am using Clear Linux. Sway should be supported. I recommend to include waybar in sway bundle and alternate the default configuration so that waybar is the default bottom bar.

**Comment by nobodyatandnothing** [comment]
unfortunately, the sway bundle has now been marked as deprecated

**Comment by pixelgeek** [comment]
https://github.com/clearlinux/clr-bundles/blob/master/bundles/sway STATUS: Deprecated
