### ISSUE TITLE
usb creater instead of dd.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1319]
i love multibootusb.

https://github.com/mbusb/multibootusb

waiting if they would create the flatpak for it. https://github.com/mbusb/multibootusb/issues/475

but it would be great if clear linux includes it as a bundle itself.

> https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#create-a-bootable-usb-drive-on-linux

using terminal for live usb in linux has to end. go for gui guys.

**Comment by OpenSourceAnarchist** [comment]
dd is one of the most simple programs to copy a disk (or disk file) to another disk. Since dd is already installed on virtually every GNU/Linux system, downloading a more complicated program seems completely unnecessary and could lead to further errors/bugs.

If you really want a GUI, just use Etcher. It's available on Windows, MacOS, and as a portable binary for Linux. But dd is always simpler and supported by almost every ISO/IMG file for Linux installations. GUI is not always needed or better.

**Comment by nazar2sfive** [comment]
dd is simpler.
but for most of us terminal is nightmare.

we want clicks not some code copy paste to terminal

**Comment by ahkok** [comment]
`xfburn` is part of Xfce and is an excellent image burning tool. It has a fairly moderate dependency footprint. `multibootusb` is PyQt5, so, a bit heavier. I wouldn't mind it if it was added, of course.

**Comment by nazar2sfive** [comment]
got fedora image writer via flathub

works great for me.

**Comment by nobodyatandnothing** [comment]
multibootusb is outdated
