### ISSUE TITLE
lttng-ust developer package

### ISSUE THREAD

**Issue by damageboy** [clearlinux/distribution#1321]
There was a [recent addition of the lttng package](https://github.com/clearlinux/distribution/issues/1269) to clear linux.

While that this is great, it seems like there is no package / way to get the lttng-ust developer related files such as headers etc. required to compile applications using lttng-ust.

Would it be possible to add such support for clearlinux?

**Comment by ahkok** [comment]
I'll add `devpkg-lttng-ust` as a bundle, which should be available in a few days.

**Comment by damageboy** [comment]
@ahkok Was I supposed to perform any action to get this?

I'm trying:

```bash
$ sudo swupd bundle-add devpkg-lttng-ust

Loading required manifests...
Warning: Bundle "devpkg-lttng-ust" is invalid, skipping it...
Failed to install 1 of 1 bundles
```

**Comment by ahkok** [comment]
@bryteise any idea why `devpkg-lttng-usr` isn't getting generated automatically? PC file name is `lttng-ust.pc` and `auto.devpkgs` entry is `lttng-ust`

**Comment by bryteise** [comment]
@ahkok The dev content needs to be in the distro at all before the devpkg shortcut can be used. It really only handles making a minimal content bundle rather than new dev content. A manual bundle should be created first for the new content cases. I pushed this so should be in for tomorrow's release.
