### ISSUE TITLE
dash to dock has only one icon highlighted (but not other opened app)

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1334]
![image](https://user-images.githubusercontent.com/12841320/66574743-7610a400-eb94-11e9-8fca-09c27f9cc85a.png)

here i have 12 app pinned to the dash to dock. out of these i have 5 app opened. but on looking at dash to dock it just seems that my one app(current active app vlc) is open as it is only highlighted. 

here dash to panel neatly shows that my 3 apps are opened.
![image](https://user-images.githubusercontent.com/12841320/66574938-d7387780-eb94-11e9-8c8b-f0dde227e4fa.png)

**Comment by mrkz** [comment]
![dash-to-dock](https://user-images.githubusercontent.com/978752/67106870-09e40080-f191-11e9-9392-eb6bd129cf7e.png)

I pinned 12 apps as well and opened a few, but I see the opened apps with no issues, Are you using the default theme provided?

Which device are you using, which CLR version and if you changed for a theme that CLR provides, which one? Otherwise I would suggest you to ensure that theme installed worked for GNOME 3.34

Closing this as it does not provides enough information. If you continue to have this problem, please either re-open and enter the missing information required to continue debugging this issue.

Thanks for your report!

**Comment by nazar2sfive** [comment]
@mrkz 
![image](https://user-images.githubusercontent.com/12841320/67162104-bd5f1780-f380-11e9-9465-a16c15c1e0de.png)


I did a complete fresh install and did full update.
The problem is still there for me.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/67307174-cc2c0280-f517-11e9-976b-2473f1f0ba59.png)

and solved

**Comment by nazar2sfive** [comment]
@mrkz requsting to change the default to "use dominant color"
