### ISSUE TITLE
Does Clear Linux provides pax package?

### ISSUE THREAD

**Issue by yangx-jy** [clearlinux/distribution#1369]
Hi,

I want to use pax command on Clear Linux so does Clear Linux provides it?

Best Regards,
Xiao Yang

**Comment by ahkok** [comment]
`pax` is an openbsd component (it's sources are part of the openbsd sources) and isn't available separately. Some people have attempted to add compatibility layers and fixes for compiling it with Linux, but these are unmaintained trees. Fedora's version hasn't been updated in 2 years and no longer has an upstream src tarball. Yoctoproject's copy is 7 years old. There are half a dozen patches needed to even make it compile.

This is one of those tools that we don't want anymore - it doesn't meet our standard for maintenance.

If I missed an actively maintained version, I'd love to hear, otherwise I'm going to close this request.
