### ISSUE TITLE
nfs-server service requires /etc/exports file

### ISSUE THREAD

**Issue by electrocucaracha** [clearlinux/distribution#1436]
It seems like this service can't start if there is no /etc/exports file. The current workaround for this is to let the creation of the file to the user before trying to start the service but this can be fix it modifying the spec file.

**Comment by ahkok** [comment]
We can not, and will not, ever, ship files in `/etc`.

NFS is by itself, without exports, something that should never, ever, start without being configured. Note that NFS is a significant security risk and should not be deployed without additional security precautions.

Therefore, it is entirely reasonable that `root` creates `/etc/exports` manually, and puts exported file systems in here manually.

Therefore, this is by design. You need to create this file manually.
