### ISSUE TITLE
xrdp > nothing after login

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1454]
Hello,

I try to connect via RDP to CL and hope to see the same as shown on the monitor. Steps taken:

```
sudp swupd bundle-add os-utils-gui
sudo systemctl start xrdp.service
sudo systemctl start xrdp-sesman.service
```

Result: Using Windows RDC tool, I get the login prompt, put in the password, connect and nothing further happens.

I found an xrdp.ini file and changed:

```
security_layer=RDP
crypt_level=none
```

to see if anything moves forward. Suddenly a connection happens and a little window shows up:

```
Connection Log 
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait ...
login failed for display 0
```

after press OK, another Window comes with the colorful xrdp logo and Session/username/password boxes

When I chose Xorg, and add the username/password, I get back to the initial "Connection Log" windows with the message: 

`login failed for display 0 `

Would be great to have a tutorial for xrdp, as things are not so simple as they should be ..

**Comment by pixelgeek** [comment]
Reproduced.  Still unclear if this is a configuration issue or a component missing from Clear Linux.

**Comment by amygilliam1** [comment]
@ahkok, can you please take a look?

**Comment by malehr** [comment]
```
# setup pam (fix login 0)
sudo cp /usr/share/pam.d/xrdp-sesman /etc/pam.d/

# fix main issue the  missing xorgxrdp
# clone and build missing drivers module xorgxrdp
git clone https://github.com/neutrinolabs/xorgxrdp

cd xorgxrdp/
# rtfm
less README.md

# run ./bootstrap and cofigure
./bootstrap
./configure

# add latest definitions missing in /usr/include/xrdp_constants.h
# I added the definitions to the source xorgxrdp/modules/rdp.h
# to avoid tainting the xrdp package ("Hash mismatch for file: /usr/include/xrdp_constants.h")
 
sed -i '/^#include "xrdp_constants.h"/a\
/* defines missing in /usr/include/xrdp_constants.h */
#ifndef WM_BUTTON8UP\
#define WM_BUTTON8UP   115\
#ifndef WM_BUTTON8DOWN\
#define WM_BUTTON8DOWN 116\
#ifndef WM_BUTTON9UP\
#define WM_BUTTON9UP   117\
#ifndef WM_BUTTON9DOWN\
#define WM_BUTTON9DOWN 118\
' ./module/rdp.h

# make 
make 
# install 
sudo make install
# add xorg config from here
sudo cp ./xrdpdev/xorg.conf /etc/X11/xrdp/xorg.conf
# create simple /etc/X11/Xsession confifg file
sudo echo ". /usr/share/defaults/xinit/xinitrc" > /etc/X11/Xsession
# (re)start xrdp service
sudo systemctl restart xrdp.service
# try to connect to xrdp 
```

**Comment by afkfurby** [comment]
what am I doing wrong?  when I try to compile xorgxrdp, I always get an xrdp not found error.
`configure: error: Package requirements (xrdp >= 0.9.0) were not met:

No package 'xrdp' found
`

and if I try to compile xrdp from source I get an error with RC4_KEY which relates to missing libssl-dev headers missing which are not included in the dev-utils-dev bundle.

**Comment by malehr** [comment]
Short update for issues in current versions of  xrdp (x11-tools)  and  xorgxrdp (git)

first issue:
configure: error: Package requirements (xrdp >= 0.9.0) were not met:
No package 'xrdp' found

Reason: 
The file /usr/lib64/pkgconfig/xrdp.pc is not installed   
(configure.log and configure script in xorgxrdp)

``` 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: xrdp
Description: An open source Remote Desktop Protocol (RDP) server
Version: 0.9.12
Cflags: -I${includedir}
```
The file is located in bundle "os-utils-gui-dev"
I installed the 3GB monster package "os-utils-gui-dev" bundle to get it.

You can try to c&p it from here or install the rpm instead
https://download.clearlinux.org/current/x86_64/os/Packages/xrdp-dev-0.9.12-36.x86_64.rpm
(but i didn't check, if this satisfies all other depedencies)

The missing mouse button definitions are fixed in current xorgxrdp, patching xrdp_constants.h  is obsolete

But xorgxrdp from git is still newer than the clr corresponding xrdp bundle!

Executing ./configure gives  
...
  checking for xrdp >= 0.9.13... no
  configure: error: Package requirements (xrdp >= 0.9.13) were not met:
  Requested 'xrdp >= 0.9.13' but version of xrdp is 0.9.12
...

To workaround this, switch the local copy back to v0.2.12 
and then run bootstrap and configure again

```
$ git checkout tags/v0.2.12
$ ./boostrap
$ ./configure
$ make 
$ sudo  make install

```
create xrdp key and cert for tls in /etc/xrdp
`$ sudo openssl req -x509 -newkey rsa:2048 -nodes -keyout /etc/xrdp/key.pem -out /etc/xrdp/cert.pem -days 365

`

**Comment by inmanturbo** [comment]
Well that's great! Thanks.

**Comment by otempia** [comment]
Issue XRDP : Display = 0 / black screen.
I wanted to compile "git clone https://github.com/neutrinolabs/xorgxrdp" but I got an error: 
configure: _error: Package requirements (xrdp >= 0.9.16) were not met_. Indeed my version of XRDP 0.9.13
No clue how to upgrade or force to upgarde xrdp to version 0.9.16.
Any work around ?
Distribution : CL Installed version: 34590
Thanks.

**Comment by mdhorn** [comment]
Bumped to 0.9.16. Should land in the next release of Clear Linux OS; 34640 or higher.

**Comment by Aqua1ung** [comment]
I am [still wrestling with xrdp](https://github.com/neutrinolabs/xrdp/issues/2599). Did you guys make it work eventually? I am using the xrdp from the [x11-tools bundle](https://clearlinux.org/software/bundle/x11-tools). Is that the proper one?
