### ISSUE TITLE
Support for AMD Radeon Pro driver

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/distribution#1460]
At the moment there is not AMD Radeon Pro driver for Clearlinux. Any change you can create a package/bundle for this driver, so the Pro features can be used.

https://www.amd.com/en/support/professional-graphics/radeon-pro/radeon-pro-wx-x100-series/radeon-pro-wx-3100

**Comment by ahkok** [comment]
Isn't that a closed source driver? We can't add those. The only thing that we can do is document how a user would install this manually. The Forum is the right place to ask for that.

**Comment by ahkok** [comment]
```
3. RESTRICTIONS

Except for the limited license expressly granted in Section 2 herein, You have no other rights in the Software, whether express, implied, arising by estoppel or otherwise. Further restrictions regarding Your use of the Software are set forth below. You may not:

    modify or create derivative works of the Software;
    **distribute, assign or otherwise transfer the Software**;
```

**Comment by JSEHV** [comment]
Can you put up a tutorial for this on https://docs.01.org/clearlinux/latest/tutorials/index.html

**Comment by lebensterben** [comment]
> Can you put up a tutorial for this on [docs.01.org/clearlinux/latest/tutorials/index.html](https://docs.01.org/clearlinux/latest/tutorials/index.html)

You should download the driver for REHL. Extract it and you will see several directories and a bash script `amdgpu-pro-install`. The later one add a local repository to `dnf`, and then calls `dnf` to install the driver.

Of course you can skip adding the local directory. In `./RPMS/x86-64` directory you would see a bunch of `rpms`, and you can manually install them. You're likely to see many failures due to dependencies, so I recommend adding the local repository and let `dnf` deal with that.

The official instruction doesn't mention anything about modifying system configurations. So I guess it's not relevant.
