### ISSUE TITLE
Systemd-logind policykit actions missing

### ISSUE THREAD

**Issue by hansinator** [clearlinux/distribution#1633]
Hi,

I recently ran into the problem that a normal logged in user can not reboot the system via command line. Clear linux is missing the config file /usr/share/polkit-1/actions/org.freedesktop.login1.policy which is part of the default systemd configuration. The file and its friends are part of the package systemd-extras which is only installed with the desktop bundle. However, systemd-logind system is partially crippled without the file. I think either the systemd-extras package should be added to the os-core-plus bundle where systemd is installed or the polkit actions should be part of the main package.

**Comment by ahkok** [comment]
No, because that would force EVERY installation to include polkit, which we absolutely do not want as a required component.

**Comment by ahkok** [comment]
`sudo reboot` is also a reasonable precaution here.

I disagree here that this is needed for every installation - we can maybe see if we can allow this to be installed optionally, but we definitely do not want this to be required.

**Comment by ahkok** [comment]
I'm relabelling this as an enhancement, as the current situation was a deliberate choice made to keep polkit out of the base install.

**Comment by ahkok** [comment]
I think the crucial question here is whether you are running with e.g. Xfce4 or Plasma and need this, or just in the console/ssh. Can you describe your use case here and what sort of environment?

**Comment by hansinator** [comment]
I am running a console-only system and I need to be able to let users restart the system f.e.
That is usually an out-of-the-box function for logged-in users. On a rather default Clear Linux install the commands "reboot" or "systemctl reboot" will fail with an error message because of the missing files mentioned above.

**Comment by hansinator** [comment]
I would not want to add extra configuration to even allow running sudo for normal users just because the distribution breaks basic systemd-logind functionality when not runnign a desktop environment.

**Comment by ahkok** [comment]
> just because the distribution breaks basic systemd-logind functionality when not runnign a desktop environment

I realize it may be frustrating, but, polkit has a hard dependency on `mozjs-60`. This package is 300mb (compressed!). It's simply unacceptable to demand that every base installation of ClearLinux must be required to provide this dependency.

This isn't about breaking systemd-logind. It rejects a user's request to reboot the system if no mechanism to elevate the user's privileges are available. As it should. This is how systemd-logind is (correctly) designed to function. Nobody broke it.

You indicate that you do not want the full desktop bundle to get this functionality. I have to investigate how we can make polkit optionally work in a console-only application that would work for your case, and I'm certainly willing to do this, but it won't be a default thing due to the sheer size of the components that it would need to make it functional.

Note: `mozjs-60` also hard requires python. The 300mb compressed number I gave earlier is not the end of it. I estimate it to come out at at least 1GB of disk space just to provide this functionality. 

I hope you can recognize the disproportional nature of the feature you request compared to what you actually get for that.

**Comment by ahkok** [comment]
I will add `systemd-extras` to the existing `polkit` bundle ... I expect this to be sufficient for console users - it provides both the action rule files, and polkit itself (with dependencies) and should therefore be the simplest solution.

**Comment by fenrus75** [comment]
also our assumption has been that on client, users are allowed to reboot,
but on servers (e.g. no gui) only root would be allowed to reboot

**Comment by hansinator** [comment]
Thanks for the insight @fenrus75 and @ahkok. I'm sorry, I wasn't aware of the complete picture.

If f.e. one tries to reboot as a normal user the first error message suggests one should install the polkit bundle. With your proposed solution it will then easily fix the situation to get the desired behaviour. When thinking about that flow it seems safe to assume that when installing the polkit bundle, the user wants it to be different from how you'd expect a usual server setup to be.

The mozjs dependency is overblown for a standard install, I agree. Times have changed with systemd.. *facepalm

**Comment by ahkok** [comment]
This should be available in today's release. `sudo swupd bundle-add polkit` and please test and let us know.
