### ISSUE TITLE
Mariadb config no effect

### ISSUE THREAD

**Issue by jh10001** [clearlinux/distribution#1634]
```
$ cat /etc/mariadb/server.cnf
[server]
bind-address=0.0.0.0
```
Bind address not change

**Comment by lebensterben** [comment]
- For references, the patch we applied for changing config dir is available [here](https://github.com/clearlinux-pkgs/mariadb/blob/3e879364d14a3a49919ac86972d6ee883e567feb/0002-Support-stateless-operation-by-migrating-to-usr-file.patch#L20-L23)
- Note that `!includeoptdir` doesn't exist in the source code of `mariadb`.
- If we intend to use `!includeoptdir` instead of `!includedir`, we need to patch `scripts/mysqld_multi.sh` file. Specifically, based on [this](https://github.com/MariaDB/server/blob/314a14f20d3ab747a3ed186b2f19b29b43dff4e8/scripts/mysqld_multi.sh#L577-L580), we can add
  ```
      elsif (/^\s*!includeoptdir\s+(\S.*?)\s*$/)
      {
        push @defaults_files, <$1/*.cnf>;
      }
  ```

**Comment by ahkok** [comment]
wow. +10 points to @lebensterben

**Comment by ahkok** [comment]
Broken due to `mariadb-10.4.6-66` which removed the patch that made this actually work in the first place. @YinThong ???

**Comment by ahkok** [comment]
Looks like we missed one other part as well to make this work.

**Comment by ahkok** [comment]
Before fix:
```
$ ss -ln|grep 3306
tcp                LISTEN              0                    0                                                                                         127.0.0.1:3306                                 0.0.0.0:*                                  
```

After fix:
```
$ ss -ln|grep 3306
tcp                LISTEN              0                    0                                                                                           0.0.0.0:3306                                 0.0.0.0:*                                  
```

Looks great to me here, pushing to build now.

`mariadb-10.4.6-78`
