### ISSUE TITLE
OpenSSL missing RC4

### ISSUE THREAD

**Issue by MarkRose** [clearlinux/distribution#1642]
While RC4 is a weak cipher, it's still used by BitTorrent. In particular, compiling https://github.com/rakshasa/libtorrent fails due to OpenSSL being compiled with no RC4 support.

Could RC4 support please be enabled?

**Comment by ahkok** [comment]
Relabelling this - we've purposely disabled `RC4` in the past. Therefore, it is not technically a bug that it is disabled.

Has the upstream project considered dropping RC4 as a requirement? We shouldn't add it back in just because of a few projects' disinterest in keeping their crypto standards updated.

**Comment by ahkok** [comment]
`libtorrent` compiles fine with `--disable-openssl`. If you rely on `RC4` to encrypt your connections, you are completely fooling yourself - read https://en.wikipedia.org/wiki/RC4

**Comment by MarkRose** [comment]
RC4 is part of the BitTorrent protocol. It's not just the library I linked, but an ecosystem of clients that rely on RC4. It's unlikely to be dropped from the protocol any time soon.

And I know it's insecure, but some clients are configured to require it.

**Comment by ahkok** [comment]
I understand - unfortunately the right solution is to fix the protocol.
