### ISSUE TITLE
`mixer build` fails if  os-core & os-core-update are not present on `mixbundles` file

### ISSUE THREAD

**Issue by lsandov1** [clearlinux/distribution#1685]
I am not familiar with the mixer tool so pardon me if this is wrong. I am trying to start with NO  `mixbundles` so I can start in a clean environment, in order words, `mixbundles` file is empty. However, seems that the tool requires at least the bundles describe in the subject, i.e os-core and os-core-update. Is this documented somewhere? are these really needed?

**Comment by jwakre** [comment]
@lsandov1 What are you trying to do? Create a minimal mix?

Mixer requires the os-core bundle to exist in the mix. Mixer injects several special case files into this bundle and all bundles in the mix are required to include it. If you want to change the packages in os-core's bundle definition, you can create a local-bundle definition for os-core and modify it.

The os-core-update bundle is optional, but its upstream bundle definition contains the necessary packages for swupd to work, so your mix likely won't be able to perform updates without it. To get your mix to work without the os-core-update bundle, set the `BUNDLE` field in the `builder.conf` file to os-core instead of os-core-update. This will add special case files required by swupd to the os-core bundle.

**Comment by lsandov1** [comment]
@jwakre thanks for your input and the details you provided.

Let me explain a bit the problem we have: we produce containers based on CLR but the problem is that runtime dependencies are taken from bundles, the latter can be quite heavy, i.e. > 8GB of runtime dependencies just to fullfill run-time dependencies. What I see is that bundles do not play so well with containers in terms of size. 

Solution: So what we want is to use the mixer to create a new set of bundles with just the packages we need so  container size is kept to minimal. As I mentioned before, we want to do the mixin at some N-1 docker stage so at the N stage, the new created bundles are just installed.  Seems to be feasible but I am not sure how to do it. 

Based on the documentation examples from [1], there are two main phases, one done in the host machine (the mixin phase) and the other done on a guest machine (the swupd bundle-add phase) and does not provide any example to do both stages in a host machine, which is basically the scenario for a docker build. I know that documention just want to provide a host-guest scenario but I would like to see a host-host scenario.

This issue can now be closed based on your description.
