### ISSUE TITLE
Missing Gnome themes, icons, extensions after update to 32360

### ISSUE THREAD

**Issue by spktkpkt** [clearlinux/distribution#1766]
After updating to 32360, all themes and icons are gone and only the default Adwaita stuff is available. Also Gnome extensions like "dash to dock" are missing.

Sidenote: `swupd repair` does nothing (no errors).

**Comment by SicLuceatLux** [comment]
I can confirm it. Materia Theme is missing. Icons on desktop also purged.

**Comment by lebensterben** [comment]
Confirm this...

**Comment by knimer** [comment]
I am using Tela icons theme. It is under:

`~/.local/share/icons/Tela`

Still the files are there. Nothing is purged.

Yet, the Tela icons theme does not appear as an option inside Gnome Tweaks application.

**Comment by antoniolopesgomes** [comment]
I also can confirm this. I was using plata-theme but now this option is gone from `gnome tweaks` and the gnome appearance reverted back to the default.

**Comment by mathewcallaghan** [comment]
Sorry to say I have the same issue.

**Comment by mrkz** [comment]
Hello,

There was a [bundle change](https://github.com/clearlinux/clr-bundles/commit/a5d6088122069576df2f6b2cd621239905b59c13) regarding the extensions and themes for desktop
In order to make theming and extensions a soft requirement (i.e: removable from the desktop bundle). While this does not affect Live iso nor new installs, clearly `also-add` is not added on bundle updates.

As a workaround in the meantime please run:
```bash
$ sudo swupd bundle-add desktop-assets-extras
```

**Comment by spktkpkt** [comment]
Just a side note: After `$ sudo swupd bundle-add desktop-assets-extras` logout and back again to activate gnome-shell user themes, reloading gnome-shell with <kbd>ALT</kbd>+<kbd>F2</kbd> and _r_ is not enough.

I'll close the bug, thank you @mrkz
