### ISSUE TITLE
Cannot be installed on emmc

### ISSUE THREAD

**Issue by virhao** [clearlinux/distribution#1792]
The emmc is visible and i even try to add needed partitons but the installer don't want recognise this as installation media even  rescan media give nothing

**Comment by mdhorn** [comment]
Can you please share what the major device is for the emmc?
`cat /proc/partitions`

I would expect 179 as the major.

I ask because we intentionally exclude a few major devices as possible installation targets:
https://github.com/clearlinux/clr-installer/blob/master/storage/storage.go#L715

My suspicion is it might incorrect be showing as major device '1'.

**Comment by ahkok** [comment]
Please include some basic information identifying the system that you are installing on: e.g. manufacturer, model/name, etc.

**Comment by ahkok** [comment]
@virhao ping - can't solve this without your help.
