### ISSUE TITLE
Intel® SSD Data Center Tool (Intel® SSD DCT) bundle for ClearLinux

### ISSUE THREAD

**Issue by mstsvetk** [clearlinux/distribution#1818]
There is [Intel® SSD Data Center Tool (Intel® SSD DCT)](https://downloadcenter.intel.com/download/29399/Intel-SSD-Data-Center-Tool-Intel-SSD-DCT-) utility distributed in rpm form. I failed to install it by mixer-tools and rpm2cpio:

$ rpm -ifv isdct-3.0.24-1.x86_64.rpm 
error: Failed dependencies:
	/bin/sh is needed by isdct-3.0.24-1.x86_64

rpm2cpio scenariofails on isdct_config.xml file absence (assume, it's generated during rpm setup):
$ isdct show -intelssd
Error: Invalid or corrupted configuration file: /etc/isdct/isdct_config.xml

Could you pls create ISDCT bundle and add it to the ClearLinux SW shop?

**Comment by lebensterben** [comment]
it's not open sourced

**Comment by ahkok** [comment]
Which means that we can't include it.

The only ticket you can file is with the support chain for this tool and ask them to create distribution neutral packaging.

Of course, it shouldn't be too difficult to obtain a proper `isdct_config.xml` file. If it is part of the `%post` scripts then you may be able to use rpm tools to extract it and view the required info. You should also inspect the rpm contents and see if the file isn't installed in another folder like under `/usr/share` or similar.

**Comment by ahkok** [comment]
I just poked at this RPM a little bit and there is no `%post` script that installs the `isdct_config.xml` file, at all. There also is no example file anywhere. From what I can see, this software is defective as is - if it doesn't run because it fails to find a required file, and that file is not provided to the user, then the software is defective. I would suggest contacting Intel Support through the software.intel.com website and opening a ticket.

I'll ask someone I know in that business unit to see if they know about it.

**Comment by ahkok** [comment]
run it under `sudo`. ..... sigh

**Comment by tinspin** [comment]
Hi, is there any place one might get a copy of this tool, intel removed it from their servers in the beginning of 2021!
