### ISSUE TITLE
ClearLinux shows black screen after boot

### ISSUE THREAD

**Issue by somequery** [clearlinux/distribution#1856]
Before, when I started the ClearLinux, it provided a promt for a password to decrypt the disk, and than provided the promt to log into the OS. It has been working properly for months.

Today morning I started the ClearLinux. After the computer started, it showed the blinking cursor in the upper, left corner of the black screen. No text was displayed since the start. Computer hangs in this sate. I tried reboot several times, but always the same result. How can I get out of this situation?

1. the OS contains just the basic packages, GNOME
2. no apps have been installed
3. prior to this issue, the OS was shutt down properly (probably 3 or 5 days ago)
4. the OS was installed from clear-30960-kvm.img

Thank you for help.

**Comment by bryteise** [comment]
You got a bit unlucky to have turned off on one of our bad LUKS builds. See [this](https://community.clearlinux.org/t/how-to-downgrade-or-repair-a-non-booting-clear-linux-install/3910/2) for details on how to repair. This issue is now fixed for the latest release once you can run swupd on your system again.
