### ISSUE TITLE
add pcie_acs_override kernel option

### ISSUE THREAD

**Issue by Tornado-Tim** [clearlinux/distribution#1863]
Wanted Clearlinux to be my host OS for a VM with GPU passthrough, then checked my iommu groups and all of my GPUs are in the same group. I don't even have the option of moving PCI-E slots to see if I can get the GPU isolated.

Which leads me here, Can the clear linux team thinking about adding a patch the kernel to add pcie_acs_override to allow a setup like mine to still proceed.

I know the risks involved in enabling it, and most people who end up adding that kernel parameter will know what they are doing.

Would just like the opportunity to use Clearlinux like this, despite been given a curve ball with the hardware I am using.

**Comment by ahkok** [comment]
On 3/30/20 12:36 AM, Tim Gunn wrote:
>
> Wanted Clearlinux to be my host OS for a VM with GPU passthrough, then 
> checked my iommu groups and all of my GPUs are in the same group. I 
> don't even have the option of moving PCI-E slots to see if I can get 
> the GPU isolated.
>
> Which leads me here, Can the clear linux team thinking about adding 
> the patch the kernel to add pcie_acs_override to allow a setup like 
> mine to still proceed.
>
> I know the risks involved in enabling it, and most people who end up 
> adding that kernel parameter will know what they are doing.
>
> Would just like the opportunity to use Clearlinux like this, despite 
> been given a curve ball with the hardware I am using.
>

This is the sort of thing that you'd build your own kernel image for - 
it's not that difficult, and stacking on a simple incremental patch, if 
properly maintained, should be easy.


Our `common` tooling makes this almost trivial, too. Run the user setup 
script, make clone_linux, cd packages/linux -> ready to patch the kernel 
spec.


We can categorically not carry out of tree patches like this because 
upstream is rejecting them for obvious reasons - we'd be very unwise to 
ignore that.


Auke

**Comment by ahkok** [comment]
As for this request, I think the answer is "no" here - we can't consider this non-upstreamable patch.
