### ISSUE TITLE
exanic.ko

### ISSUE THREAD

**Issue by flare04** [clearlinux/distribution#1907]
Hi can this module be added please ?  the source code can be found at https://github.com/exablaze-oss/exanic-software

**Comment by ahkok** [comment]
In general: No - we don't merge out-of-tree kernel drivers that are not going to, or are not submitted to be merged upstream. Since this driver is GPL licensed, it should be submitted to the upstream Linux kernel instead.

I see no reason to make an exception in this case. Use the DKMS method to install it manually if you need.
