### ISSUE TITLE
Need Python-ZSI for SOAP authentication

### ISSUE THREAD

**Issue by szollin** [clearlinux/distribution#201]
Trying to get 802.1X authentication work but, I need the Python-ZSI module to authenticate with SOAP for certificate import. Please add this package to the python-extras bundle

```
$ ./UserRAWS.py
Error: Python-ZSI module is missing
```

**Comment by mrkz** [comment]
@szollin we are not going to ship python-ZSI modules due to being 12 years old and unmaintained.

However, we do have a python module to talk SOAP, try taking a look at [python-zeep](https://github.com/clearlinux-pkgs/python-zeep).

If you still want to install the old python-ZSI module, I recommend you to go with [Python virtualenv](https://virtualenv.pypa.io/en/stable/)
