### ISSUE TITLE
Enhancement: Prompt User for Swap Size When Using Automatic Partitioning

### ISSUE THREAD

**Issue by mandersendev** [clearlinux/distribution#2039]
During an evaluation install of Clear I encountered several bugs with manual partitioning and FDE which have been opened as a separate bug issue (#2038). Afterwards, I accepted the default partitioning scheme to try and get to a bootable system to continue evaluation. Fortunately, that worked, but it left me with only 64MB (no typo) of swap on a 128GB drive and no way to modify that value except through the advanced partitioning which was crashing the installer.

64MB of swap might as well be 0. I'm not sure why the installer thinks swap is of little value, because there's a lot of us who really need it. I couldn't deploy Clear today if I wanted to because the installer crashes when trying to manually partition a workable swap size.

**Feature Enhancement**: When a user selects to use the default partitioning scheme, a prompt should be displayed querying the desired amount of swap space, since this is one of the two biggest changes (the other being FDE) a sysadmin typically makes when provisioning a system intended for use as a node in a pool/swarm/cluster. Additionally, the default suggested value should be reasonable - perhaps 1:1 with system memory, capped by the lower of a hard ceiling and a percentage of the installation drive.

**The engineering time cost should be minimal**, as it requires only one numeric text prompt (number + optional "M" or "G" modifier) prior to the autopartitioning algorithm laying out the disk.

Even though extensive regular use of swap isn't always ideal in production, having ample available is useful for certain use cases, as well as for application diagnostics when memory usage far exceeds engineering expectations. A large swap at least lets logging facilities understand what is going on and how far the problem would have gone, rather than the system hitting out of memory exceptions which limit diagnostic insights and responses.

Without ample swap, we don't know what caused the problem or even how big it is. Root causes could include: a genuine shortage of memory in a particular node configuration, a sudden spike in load requiring mitigation, a bug resulting in unexpectedly high consumption under specific circumstances, or a denial of service vulnerability requiring immediate triage.

Additionally, user-configurable swap with otherwise default parameters makes sense given the state of disks and nodes today.

For example, our nodes don't need more than 64GB of local storage right now, and it's not likely that going beyond 128GB would serve any practical value in the near future. However, the need for low-latency, high-speed local access over PCIe limits us to current generation drives with capacities far exceeding storage requirements, from which subtracting 64GB in swap constitutes a loss of nothing. Might as well overprovision it.

This is increasingly a common case among clustered nodes connected at 10, 25, or 40 Gbps to highly performant and fault tolerant databases, file stores, and object stores. Our nodes run at 40 because a NIC costs $30 and a DAC $15, letting the node read/write to persistent network storage faster than it can its own local storage. If swap weren't needed, our nodes would be totally diskless, and we'd reengineer how we use available local space as scratch (because its there) rather than hitting the network.

***(In case anyone from Intel is reading [thank you for your sponsorship of Clear BTW!] - there's an unmet and growing need for 64GB/128GB M.2 Optane modules using the latest process and controller technology for thinner nodes which need a limited amount of local storage but with excellent latency, random access, write endurance, and a very low uncorrected bit error rate. The 900p series doesn't have a high density node-friendly form factor (ours are a 3" vertical package and connections only for power, Ethernet, and cooling - no space to mount anything 2.5") and the lowest capacity 905p in M.2 is too large/costly at 380GB and would increase node cost by nearly 50%. We love the 1.5TB 905p in our storage and database servers, though, because performance is so great we built a cluster of COTS nodes around them.)

**Comment by mdhorn** [comment]
@mandersendev Thank you for your feedback and request.

The use of swap and the sizing is a very contentious business.

As I recently stated in request to have ["no swap"](https://github.com/clearlinux/clr-installer/issues/748): 
"The Clear Linux OS architecture team determined that having a small amount of swap is a requirement for the OS, and hence the required default with the interactive installer. The default is now to create a small swap file for interactive installation (as of 2.5.0 release); which can then be easily deleted if not desired."

The amount of swap needed is really a combination of the hardware used and the use case. The default small swap size was chosen for most interactive desktop or server installations.  Advanced Configuration is the right choice for custom installation where you might want a swap partition.

Part of the move to the swap file was to more easily allow people to more easily change the swap after installation. The swap file can be removed, or replaced to adjust the needs of the use case. Also, a swap file is easier to adjust if the use case changes or is different from the initial expectations.

Because of all of this, we opted to not allow the user to adjust the swap size during the default interactive installation and not plans to make this change in the future.

The installer crashing when attempting to use the Advanced option is a different problem and should be investigated.
