### ISSUE TITLE
Add a gaming kernel with fsync patches or add it to the main kernel?

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2052]
Then patch the wine on Clear Linux with fsync patches?

**Comment by romulasry** [comment]
https://xanmod.org/

**Comment by insilications** [comment]
I wonder how different is this kernel from the current kernel-rt

**Comment by thiagomacieira** [comment]
By policy, we will not patch the kernel, aside from minor things we've developed to change some performance defaults. It has to be an upstream-maintained tree, like the stable, LTS and RT. Otherwise, it's a nightmare to keep up-to-date.

If you have suggestions for CONFIG options we should change to improve performance for certain scenarios, please say so.
