### ISSUE TITLE
Libreswan pluto crashes with assertion failure in 33590

### ISSUE THREAD

**Issue by topcat001** [clearlinux/distribution#2087]
After updating from 33540 to 33590 pluto (part of Libreswan) crashes at startup (while trying to establish an L2TP VPN). The issue is identical to https://github.com/libreswan/libreswan/issues/342 which explains the problem. After reading the explanation I believe it is caused by the nss update in 33550. This basically renders Libreswan unusable.

Apparently this can be fixed by compiling Libreswan with the correct nss headers. Upstream also mentions a patch which prevents Libreswan from encountering this problem no matter what the version of nss.

I downgraded to 33540 and it is working again.

**Comment by lebensterben** [comment]
> A version of this patch is already in git master, so will be in the next release of libreswan.

https://github.com/libreswan/libreswan/issues/342#issuecomment-631538563

Why are they not making a bug-fix release?

**Comment by topcat001** [comment]
I guess we'll have to wait for the next release. It's a shame because I cannot upgrade till then.

**Comment by phmccarty** [comment]
I have set `-DNSS_PKCS11_2_0_COMPAT=1` as a preprocessor flag for the libreswan build. The fix should land in Clear within a couple of business days (early next week).

**Comment by topcat001** [comment]
That's great news! I'll try it out and report back.

**Comment by dkosovic** [comment]
The gcc `ffat-lto-objects -flto=4` flags are another reason for a libreswan segfault, although I did set `use_lto = false` in a previous patch I posted in issue https://github.com/clearlinux/distribution/issues/1830 which also had the patch for NSS >= 3.52 .

Also as mentioned in issue https://github.com/clearlinux/distribution/issues/1830 , NSS's `/usr/bin/certutil` from the cryptography bundle is required, otherwise libreswan will segfault as the NSS database won't get initialized when using certificates. For the time being, the workaround is to explicitly install the cryptography bundle:
```
sudo swupd bundle-add cryptography
```

Find the changes I've done against the current version of libreswan for better stateless support, FHS compliance, aditional features and NetworkManager-l2tp compatibility, here:
* https://github.com/dkosovic/libreswan/commit/5a60145e0529fe6828850b0599a091ee8f0489f0

and the corresponding patch is:
* https://github.com/dkosovic/libreswan/commit/5a60145e0529fe6828850b0599a091ee8f0489f0.patch

**Comment by topcat001** [comment]
I updated today to 33620 and pluto no longer crashes. Thanks! I think we can close this issue.

**Comment by phmccarty** [comment]
Thanks for confirming the fix!
