### ISSUE TITLE
`emacs` 27.1 seems to be broken

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2095]
Upon opening `emacs`, it reports an error:

> Warning (initialization): An error occurred while loading '/home/lucius/.emacs.d/init.el':
>
> Symbol's value as variable is void: \213

And it suggested me to run `emacs --debug-init`, whose output is attached here: [bug.log](https://github.com/clearlinux/distribution/files/5066896/bug.log)

This issue doesn't appear in flatpacked emacs, so it shouldn't be resulted from my current emacs customizations.

**Comment by phmccarty** [comment]
I don't see this error when running latest emacs, though the `~/.emacs.d` directory on this system is empty... If you try launching it without customizations, do you still see the same issue?

**Comment by phmccarty** [comment]
Also, I am seeing other related reports, but it's not clear to me whether a root cause is known.

https://github.com/syl20bnr/spacemacs/issues/11585
https://github.com/flathub/org.gnu.emacs/issues/19

**Comment by phmccarty** [comment]
Based on your backtrace, it looks like you are using spacemacs from the develop branch, since I don't see any code related to the new pdump feature on the master branch.

Note that I [disabled pdump](https://github.com/clearlinux-pkgs/emacs/commit/8a11bf063e098c0) in the packages because emacs would not start for me otherwise. That issue might be related to the [patch we carry](https://github.com/clearlinux-pkgs/emacs/blob/8a11bf063e098c0/0001-Make-the-emacs-compiled-without-X11-call-the-one-com.patch), but I haven't investigated it yet, because the legacy unexec configuration worked for me.

I figured I would mention this, in case the issue is related to spacemacs with pdump being disabled.

**Comment by lebensterben** [comment]
>I don't see this error when running latest emacs, though the `~/.emacs.d` directory on this system is empty... If you try launching it without customizations, do you still see the same issue? ...

@phmccarty I can confirm that the problem disappeared once I moved ~/.emacs.d away.

And indeed I'm using spaxemacs. So I guess this is a Spacemacs issue.

**Comment by lebensterben** [comment]
This error never occurred prior to 27.1 and I have always keep Spacemacs updated. 

Interestingly, the two issues mentioned above shows that this error occurs to both flatpaked Emacs and native Emacs. It also occurs on Emacs 26.

I'm not sure whether disabling pdump is the cause here.

**Comment by lebensterben** [comment]
@phmccarty I just found the bug disappeared and I'm able to use `emacs-x11` with Spacemacs.

For future references, below are the enabled features for `emacs-x11` and Flatpak emacs:

## `system-configuration-features`
### Both
`XPM JPEG PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2 GMP`
### `emacs-x11`
`IMAGEMAGICK GPM UNEXEC`
### Flatpak Emacs
`TIFF GIF LIBSELINUX PDUMPER`
