### ISSUE TITLE
Since the last version of clear : evolution freeze

### ISSUE THREAD

**Issue by JPhilippeBoulanger** [clearlinux/distribution#2135]
@clear-jpb~ $ swupd check-update
Current OS version: 33760
Latest server version: 33760
There are no updates available
@clear-jpb~ $ evolution

** (evolution:5198): ERROR **: 07:43:16.942: Failed to start dbus proxy: L’exécution du processus fils « /usr/bin/xdg-dbus-proxy » a échoué (Aucun fichier ou dossier de ce type)

(evolution-alarm-notify:5207): GLib-GIO-WARNING **: 07:43:16.952: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
Trappe pour point d'arrêt et de trace (core dumped)
@clear-jpb~ $

**Comment by phmccarty** [comment]
Thanks for the report.

I noticed this issue as well recently, though my fix didn't land in time for 33760. webkitgtk has a runtime requirement for xdg-dbus-proxy, but it was not declared for the package. I added the dependency for webkitgtk, and it will be fixed in the next build (early next week).

As a workaround until then, you could bundle-add one of the larger bundles that installs xdg-dbus-proxy, or you could install the rpm manually. Something like:

```
$ curl -O https://cdn.download.clearlinux.org/releases/33760/clear/x86_64/os/Packages/xdg-dbus-proxy-bin-0.1.2-2.x86_64.rpm
$ rpm2cpio xdg-dbus-proxy-bin-0.1.2-2.x86_64.rpm | ( cd /; sudo cpio -iduv )
```

**Comment by JPhilippeBoulanger** [comment]
Thank you.
By installing the Gnome version instead of the FlatPack version, everything is back to normal.
