### ISSUE TITLE
nfs-server fails to start due to rpcbind aborting

### ISSUE THREAD

**Issue by ljmccarthy** [clearlinux/distribution#2188]
Discussion of the issue here: https://community.clearlinux.org/t/nfs-server-failing-after-restart/5644

System log for rpcbind:
```
systemd[1]: Starting RPC bind service...
systemd[1]: Started RPC bind service.
sudo[1049]: pam_unix(sudo:session): session closed for user root
rpcbind[1053]: svc_run returned unexpectedly
systemd[1]: Started Process Core Dump (PID 1056/UID 0).
systemd[1]: rpcbind.service: Main process exited, code=dumped, status=6/ABRT
systemd[1]: rpcbind.service: Failed with result 'core-dump'.
systemd-coredump[1057]: Process 1053 (rpcbind) of user 0 dumped core.
                     
                           Stack trace of thread 1053:
                           #0  0x00007ff238efdd65 __GI_raise (libc.so.6 + 0x41d65)
                           #1  0x00007ff238ee1889 __GI_abort (libc.so.6 + 0x25889)
                           #2  0x0000557606f79d86 main (rpcbind + 0x3d86)
                           #3  0x00007ff238ee3dbd __libc_start_main (libc.so.6 + 0x27dbd)
                           #4  0x0000557606f7a37e _start (rpcbind + 0x437e)
systemd[1]: systemd-coredump@5-1056-0.service: Succeeded.
```

**Comment by phmccarty** [comment]
Thanks for the report!

This is a puzzling bug, but disabling LTO for rpcbind appears to be a workaround.

LTO was enabled in the latest change to the [rpcbind package](https://github.com/clearlinux-pkgs/rpcbind/commit/299c8d43ff), which results in the rpcbind binary aborting after the daemonized process [returns early](https://git.linux-nfs.org/?p=steved/rpcbind.git;a=blob;f=src/rpcb_svc_com.c;h=9c1c3af03cd6602bba0d69a5fa8b32979d8a0dd0;hb=c0c89b3bf2bdf304a5fe3cab626334e0cdaf1ef2#l1061) (not via signal handler). When LTO is *not* enabled, the rpcbind binary does not abort and appears to function as it did previously.

Should be fixed in 33950 or newer.

**Comment by phmccarty** [comment]
The `rpcbind` package has been rebuilt with LTO disabled, and the change landed in release [33960](https://cdn.download.clearlinux.org/releases/33960/clear/RELEASENOTES-33940-to-33960).
