### ISSUE TITLE
`gnome-video-effects` package is using a different `pkg-config` directory

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2194]
https://github.com/clearlinux-pkgs/gnome-video-effects/blob/cf14489b2b0b8552cff669611b175ca90010968b/gnome-video-effects.spec#L105

Normally, on Clear Linux packages install their `*.pc` files to `/usr/lib64/pkgconfig` and `/usr/lib32/pkgconfig`.

Maybe this package is mis-configured?

**Comment by phmccarty** [comment]
@lebensterben `/usr/share/pkgconfig` is in the pkg-config lookup path, so this shouldn't pose a problem. If `gnome-video-effects` shipped other development files, then rpm dependencies would not be wired up correctly, and in that case, I agree that it should be moved to `/usr/lib64/pkgconfig`.

Note that I fixed a different package (`spice-protocol`) recently for that exact reason. The [update to 0.14.3](https://github.com/clearlinux-pkgs/spice-protocol/commit/6b4919d20a2ae22cff30deced90ba9afc734e64a) resulted in the pkgconfig file being moved to `/usr/share/pkgconfig`, but this broke package dependencies: `spice-protocol-data` did not depend on `spice-protocol-dev`, so the build broke for all packages with a build requirement on either `spice-protocol-dev` or `pkgconfig(spice-protocol)`. My [fix](https://github.com/clearlinux-pkgs/spice-protocol/commit/1db463468fe111e9cab54173571cf97391c42ac3) was to install it to `/usr/lib64/pkgconfig` again so that autospec would bin it in `spice-protocol-dev`.

**Comment by lebensterben** [comment]
Okay. Thanks for you explanation.
I'm closing it now since currently there's no known bugs cause by this.
