### ISSUE TITLE
Dot (graphviz) cannot generate PNG/PDF files

### ISSUE THREAD

**Issue by topcat001** [clearlinux/distribution#2238]
I have the `graphviz` bundle installed on my system. I noticed that it is missing some output formats, most notably PDF and PNG.

```
$ dot -Tpng
Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pic plain plain-ext pov ps ps2 svg svgz tk vdx vml vmlz xdot xdot1.2 xdot1.4 xdot_json
```

I have tried running
```
sudo dot -c
```
but it makes no difference. It looks like it might be an issue with the package build.
Current OS version: 34130

**Comment by phmccarty** [comment]
I can't reproduce the issue... Tested with:
```
systemd-analyze dot | dot -Tpng > test.png
systemd-analyze dot | dot -Tpdf > test.pdf
```
Do you see the same problem with 34140?

**Comment by phmccarty** [comment]
I am enabling graphviz's ghostscript plugin, since the configure script has not been detecting the ghostscript headers for a while. Presumably this will help with the PDF output, though I haven't researched much yet. And it doesn't explain why the PDF output works for me *without* the ghostscript plugin enabled.

**Comment by topcat001** [comment]
I just upgraded to 34140. However PNG and PDF are still missing. My `/var/lib/graphviz/config6` file is as follows (in case that helps):
```
# This file was generated by "dot -c" at time of install.

# You may temporarily disable a plugin by removing or commenting out
# a line in this file, or you can modify its "quality" value to affect
# default plugin selection.

# Manual edits to this file **will be lost** on upgrade.

libgvplugin_core.so.6 core {
	device {
		dot:dot 1
		gv:dot 1
		canon:dot 1
		plain:dot 1
		plain-ext:dot 1
		xdot:xdot 1
		xdot1.2:xdot 1
		xdot1.4:xdot 1
	}
	device {
		fig:fig 1
	}
	device {
		ismap:map 1
		cmap:map 1
		imap:map 1
		cmapx:map 1
		imap_np:map 1
		cmapx_np:map 1
	}
	device {
		mp:mp -1
	}
	device {
		ps:ps 1
		ps2:ps 1
		eps:ps 1
	}
	device {
		svg:svg 1
		svgz:svg 1
	}
	device {
		json:json 1
		json0:json 1
		dot_json:json 1
		xdot_json:json 1
	}
	device {
		tk:tk 1
	}
	device {
		vml:vml 1
		vmlz:vml 1
	}
	device {
		pic:pic -1
	}
	device {
		pov:pov 1
	}
	render {
		dot 1
		xdot 1
	}
	render {
		fig 1
	}
	render {
		map 1
	}
	render {
		mp -1
	}
	render {
		ps 1
	}
	render {
		svg 1
	}
	render {
		json 1
		json0 1
		dot_json 1
		xdot_json 1
	}
	render {
		tk 1
	}
	render {
		vml 1
	}
	render {
		pic -1
	}
	render {
		pov 1
	}
	loadimage {
		png:svg 1
		gif:svg 1
		jpeg:svg 1
		jpe:svg 1
		jpg:svg 1
		png:fig 1
		gif:fig 1
		jpeg:fig 1
		jpe:fig 1
		jpg:fig 1
#FAILS		png:vrml 1
#FAILS		gif:vrml 1
#FAILS		jpeg:vrml 1
#FAILS		jpe:vrml 1
#FAILS		jpg:vrml 1
		eps:ps 1
		ps:ps 1
		(lib):ps 1
		png:map 1
		gif:map 1
		jpeg:map 1
		jpe:map 1
		jpg:map 1
		ps:map 1
		eps:map 1
		svg:map 1
		png:dot 1
		gif:dot 1
		jpeg:dot 1
		jpe:dot 1
		jpg:dot 1
		ps:dot 1
		eps:dot 1
		svg:dot 1
		png:xdot 1
		gif:xdot 1
		jpeg:xdot 1
		jpe:xdot 1
		jpg:xdot 1
		ps:xdot 1
		eps:xdot 1
		svg:xdot 1
		svg:svg 1
		png:vml 1
		gif:vml 1
		jpeg:vml 1
		jpe:vml 1
		jpg:vml 1
		gif:tk 1
	}
}
libgvplugin_dot_layout.so.6 dot_layout {
	layout {
		dot 0
	}
}
libgvplugin_neato_layout.so.6 neato_layout {
	layout {
		neato 0
		fdp 0
		sfdp 0
		twopi 0
		circo 0
		patchwork 0
		osage 0
		nop 0
		nop1 0
		nop2 0
	}
}
libgvplugin_visio.so.6 visio {
	device {
		vdx:visio 1
	}
	render {
		visio 1
	}
}
libgvplugin_webp.so.6 webp {
	device {
#FAILS		webp:cairo 1
	}
	loadimage {
#FAILS		webp:cairo 1
	}
}
```

**Comment by topcat001** [comment]
Perhaps I'm missing some other package which the configuration step needs to enable these formats during install?

**Comment by phmccarty** [comment]
@topcat001 I think I see what's happening. Some of the `graphviz` content is installed in the `graphviz-extras` subpackage to reduce install footprint of the `graphviz` bundle, and that `graphviz-extras` package is required for support of PDF, PNG, and probably other formats. That package is available in these bundles:

```
R-extras-dev
desktop-apps
desktop-dev
games-dev
kde-frameworks5-dev
kvm-host-dev
os-clr-on-clr-dev
os-utils-gui-dev
qt-basic-dev
software-defined-cockpit-dev
user-basic-dev
```

Some of those bundles are quite large... You can check the installation footprint for each by running:

```
sudo swupd search-file /usr/lib64/graphviz/libgvplugin_gd.so
```

And then pick the most appropriate bundle for your install.

I have both the `kvm-host-dev` and `qt-basic-dev` bundles installed on my local system, which I think explains why it works for me.

That being said, it would be nice if `graphviz-extras` could be added to another bundle with smaller footprint so that you don't need to install one of those large -dev bundles (or `desktop-apps`, which is also quite large). Let me know if you have any suggestions.

**Comment by phmccarty** [comment]
I suppose we could add a `graphviz-extras` bundle that the subpackage with the same name, since we've created similar bundle pairs in the past, like `xscreensaver` and `xscreensaver-extras`...

**Comment by topcat001** [comment]
Beautiful! Thank you very much! Yes it would be nice to separate it out, but for now this workaround is good for me. I'll report back in a sec.

**Comment by topcat001** [comment]
I installed `desktop-apps` as that's the smallest and now dot is able to create both PDF and PNG files. I'm going to close this, thanks! Please consider making a `graphviz-extras` bundle when possible.
