### ISSUE TITLE
RFE: please consider updating go to 1.16

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#2326]
Hi all, 

went public in [February](https://golang.org/doc/go1.16) and there's an increasing amount of stuff that just expects it to be available to build due to its new [features](https://blog.golang.org/go116-module-changes). 

All the best, 

António

**Comment by mdhorn** [comment]
There is a bit of effort here for us to enable go 1.16, mostly due to [the changes in how modules are handled](https://blog.golang.org/go116-module-changes).

We have a list of packages we need to rebuild when we update go versions, and many of them won't build right now with 1.16 without updates. We will work on patching them locally as time allows, but upstream fixes would be a help.

**Comment by phmccarty** [comment]
@mdhorn is working on this update.

**Comment by mdhorn** [comment]
Fixed in 34850 or higher

```
$ swupd info
Distribution:      Clear Linux OS
Installed version: 34850
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
$ go version
go version go1.16.5 linux/amd64
```
