### ISSUE TITLE
sse 4.2

### ISSUE THREAD

**Issue by himaj264** [clearlinux/distribution#2353]
![error](https://user-images.githubusercontent.com/83090986/117474321-717ebe00-af78-11eb-80df-5894e8adc7a7.JPG)
please help

**Comment by himaj264** [comment]
after meson build

**Comment by thiagomacieira** [comment]
It goes a lot easier if you copy the text from the terminal and paste into the bug report, instead of attaching a screenshot. include the full output, even. I can't copy & paste the text from your screenshot.

Please explain what your issue has to do with Clear. Is this a regular build of DPDK on Clear? What command-line did you use for meson?
