### ISSUE TITLE
Unable to set memlock unlimited

### ISSUE THREAD

**Issue by qumaciel** [clearlinux/distribution#2372]
I am trying to set memlock unlimited to my user, but with no success.

I've followed [/etc/security/limits.conf not loaded on boot](https://community.clearlinux.org/t/etc-security-limits-conf-not-loaded-on-boot/2210) and [Unable to set nofiles soft limit](https://community.clearlinux.org/t/unable-to-set-nofiles-soft-limit/4445):

* copied `common-session` from `/usr/share/pam.d` to `/etc/pam.d/`
* added `username - memlock unlimited` to `/etc/security/limits.conf` 
* added `session required pam_limits.so conf=/etc/security/limits.conf ` to `/etc/pam.d/common-session`
* rebooted
* checked, but I still got the default value
```
$ ulimit -l
64
```

This should work, as far as I know. I don't know what is happening.

**Comment by qumaciel** [comment]
I am trying to use JACK2, but it is pointless without this.

**Comment by phmccarty** [comment]
@qumaciel Based on the mailing discussion, it sounds like you have resolved the issue? If so, feel free to post any details about how you solved it.

**Comment by qumaciel** [comment]
Sure, I forgot to update this thread.

It appears that CL handles the memlock limit via systemd, not PAM.
Thus, to increase the limit, I've modified both `/etc/systemd/system.conf ` and `/etc/systemd/user.conf`, including:
```
[Manager]
DefaultLimitMEMLOCK=infinity
```
I am still not sure why I had to change both of them; modifying `/etc/systemd/user.conf` should be enough.

Anyway, after rebooting, I've got:
```
$ ulimit -l
unlimited
```

**Comment by phmccarty** [comment]
Thanks!

I suspect the reason why you needed to set both is because `/etc/systemd/user.conf` is only relevant to services managed by `systemd --user` instances, and `/etc/systemd/system.conf` is relevant to system services managed by PID 1 systemd... It's common to see non-privileged processes be members of the _user slice_ for a given user (`user-UID.slice` unit, the child of `user.slice`) instead of the that user's _user instance_ (`user@UID.service`).

So if you wanted to set global limits for a specific user via systemd, consider exploring settings for `user-UID.slice` for the user. Looking at the systemd.slice(5) man page, I am referred to systemd.resource-control(5). Some limits are described there, but nothing for adjusting MEMLOCK limits that I can see.
