### ISSUE TITLE
update neovim to 0.5.1

### ISSUE THREAD

**Issue by azazazgwerbv** [clearlinux/distribution#2436]
https://github.com/neovim/neovim/releases

**Comment by fenrus75** [comment]
so eh.. since you're clearly using neovim more than I do (I'm a joe user,
sorry)

how reliable are the neovim updates? Are they something that we can safely
turn on auto-update for?
(we have tools that for approved packages, basically automatically follow
upstream releases.. we only
do that for things we're confident that they don't have too many broken
updates)

**Comment by azazazgwerbv** [comment]
i don't know, but bear in mind that it is called stable as opposed to the nightly version.

**Comment by phmccarty** [comment]
Integrated in release 35080
