### ISSUE TITLE
libdw segfaults (again?)

### ISSUE THREAD

**Issue by mmorini** [clearlinux/distribution#2440]
My log is filling with hundreds of

[978059.813693] crashprobe[2180844]: segfault at 8 ip 00007f0aa830d9dd sp 00007ffe235d7ed0 error 4 cpu 10 in libdw-0.185.so[7f0aa82cf000+46000]

I understand something's off on other distributions too ( https://githubmemory.com/repo/dyninst/dyninst/issues/1061 ), and the now closed issue https://github.com/clearlinux/distribution/issues/2297 seemed related to a custom gnome configuration; I'm running headless, though.

#swupd info
Distribution:      Clear Linux OS
Installed version: 35050
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

**Comment by phmccarty** [comment]
Thanks for the report.

I can reproduce the issue. The crash could be related to the one mentioned at #2297, but I haven't tested that release to verify. However, this particular crash is fixed with:

https://sourceware.org/git/?p=elfutils.git;a=commitdiff;h=828024afc5

That patch landed after the elfutils 0.185 release (current latest), so I will backport it for Clear.

**Comment by mmorini** [comment]
Thank you kind sir.

**Comment by phmccarty** [comment]
Fixed in release 35100
