### ISSUE TITLE
wlan requires UseDomains in order for autoproxy to work

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#25]
reported by @rustylynch

When connecting to a wifi network behind a firewall the autoproxy is unable to resolve the PAC url because the 80-wlan.network configuration file is not enabling UseDomains=yes in the [DHCP] section.
Index: clr-systemd-config-149/network/80-wlan.network

--- clr-systemd-config-149.orig/network/80-wlan.network 2018-02-08 11:48:27.000000000 -0800
+++ clr-systemd-config-149/network/80-wlan.network 2018-03-17 18:56:18.586759088 -0700
@@ -5,4 +5,5 @@
DHCP=both

[DHCP]
+UseDomains=yes
UseMTU=yes

**Comment by ahkok** [comment]
This is debatable, and certainly not something I think we should add by default.

See https://www.freedesktop.org/software/systemd/man/systemd.network.html:

```
It is recommended to enable this option only on trusted networks, as setting this affects resolution of all host names, in particular of single-label names. It is generally safer to use the supplied domain only as routing domain, rather than as search domain, in order to not have it affect local resolution of single-label names.
```

I think you would want to copy `80-wlan.network` to `/etc/systemd/network` and add the option there.

**Comment by ahkok** [comment]
Closing wontfix because the fix is too risky.

**Comment by rustylynch** [comment]
Note that the fix already landed so you will need to re-remove the change.

After this is removed, how would you recommend users identify a given wifi network as trusted so that autoproxy works?  Is is the expectation that the implementation of autoproxy needs to change?

**Comment by ahkok** [comment]
Asking the user interactively whether a proxy should be trusted is likely always the wrong thing to do, because people will just click "yes, trust this proxy" without hesitation.

I can only imagine that a stronger level of trust needs to be used, such as checking an SSL certificate, but even that is problematic due to not having any way to verify that the original search domain given by the DHCP server is entirely untrustable. This isn't usually a big issue on ethernet networks, but on wifi networks I see no solution. I've given this some thought now several times, and any solution that would approach the problem would mean a standards change as well, so I'm pretty stumped.
