### ISSUE TITLE
Documentation Wrong

### ISSUE THREAD

**Issue by uudruid74** [clearlinux/distribution#250]
The Getting Started Guide gives a curl command to download the latest version.  It fails, File Not Found.  Apparently the file structure has changed.  Please update documentation

**Comment by puneetse** [comment]
@uudruid74 thank you for raising the issue. 

The documentation repo would be a better place to file this issue ( https://github.com/clearlinux/clear-linux-documentation/issues ). If you can include some specific example links, that would be great too because I am not seeing the issue on all curl examples.

**Comment by ahkok** [comment]
From time to time this may happen. The only right thing to do is to keep the command independent of version numbers in the way it is done. Changing it would mean more problems.

If it happens consistently for several days, let us know.

for reference, I assume you're talking about this curl command:

`curl -O https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz`
