### ISSUE TITLE
rework cloud native bundles

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#256]
Currently, ```sudo -E swupd bundle-list -D containers-basic``` gives

```
  * containers-virt
    |-- cloud-native-basic
```

From cloud-native-basic (essentially kubernetes) perspective, this is annoying/wrong because when installing cloud-native-basic, kata is the first dependency and kata depends on the container runtime.

It should be:
- install cloud-native-basic
- cloud-native-basic depends on default container-runtime-xxx
- all container-runtime-xxx's depend on containers-virt

**Describe the solution you'd like**
split containers-basic to multiple containers-runtime-xxx (docker, containerd, cri-o) and modify the dependencies. Have cri-tool, cni/cni-plugins in cloud-native-basic.

**Comment by bryteise** [comment]
@mythi containers-virt is intended to not be required by containers-basic (which is intended to provide the ability to run oci compatible container images + docker extensions for container images essentially) because runc is the lowest common denominator runtime in my view (open to changing this opinion though). I'm happy to change what cloud-native-basic pulls in for its default runtime and cut off includes since we want to have a more tailored bundle though.

**Comment by mythi** [comment]
kata-runtime is an alternative to runc. the kubernetes flow is: kubernetes CRI -> [cri-o|containerd|docker(shim)|...] -> [runc|kata-runtime|gvisor|...]. kubernetes uses containers-basic. containers-virt complements that.

**Comment by ahkok** [comment]
@eljuarez is this something you can help with?

**Comment by eljuarez** [comment]
So what I think the most common use case for k8s is to use them with "normal" containers (containers-basic) but in the bundle definitio for cloud-native-basic containers-virt (kata) is included instead. @miguelinux you mentioned that there was a reason for this. Can you share why this is the case?

**Comment by bryteise** [comment]
@eljuarez So the cloud-native-basic pulls in kata (and runc since kata pulls runc) because cloud-native-basic currently defaults to the kata-runtime when running an untrusted workload. If we want to change this default and just make users set this themselves then we could have cloud-native-basic pull in just containers-basic.

**Comment by miguelinux** [comment]
containers-basic is included by containers-virt, so as I can see in the history

https://github.com/clearlinux/clr-bundles/commit/4ec8a55d43fbb26ac7f414025048b49333b7151e
and
https://github.com/clearlinux/clr-bundles/commit/d6fcffef778e20f9b736ecf4ead4f47659006af8
 
The idea was k8s manage Kata (CC before) at this level.

So as this is a basic bundle, I figure out that it should contains only "classic" containers with k8s.

Thoughts?

**Comment by mythi** [comment]
> defaults to the kata-runtime when running an untrusted workload

With k8s ```RuntimeClass```, introduced in 1.12 (still "alpha" though), the notation of trusted/untrusted will be deprecated. (To me,) It's almost like lifting kata equal citizen to runc. That change is one of the reasons why I triggered this issue/conversation.

The fundamental reason for this issue is that I think we should allow more freedom for users to decide which CRI they wish to use and not force them to, e.g., install docker as it's strictly not needed anymore (by k8s).

The change(s) could be something like:

- make pundles out of docker, cri-o, containerd (and each of them would depend on containers-basic)
- add runc in containers-basic
- set containers-basic to depend on one of the CRI pundles (k8s now defaults to cri-o)
- set containers-basic to depend on containers-virt
- drop containers-basic dependency in containers-virt (not necessary)

**Comment by AntonioMeireles** [comment]
FWIW ... i'm mostly with @mythi on this one :-) *but* _OTOH_ the elephant in the room (already being discussed elsewhere) is to get k8s packaging right to keep things rolling _ad eternum_ :-) and in that regard this is subsidiary to that. 

All the best, 

António

**Comment by mythi** [comment]
@AntonioMeireles only *mostly*? :) besides the conversation in #203, is there anything else you think could change?

**Comment by pohly** [comment]
One observation: when installing just `cloud-native-basic` (as instructed in https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes) on Clear Linux 26410, `containers-basic` does not get installed and starting some pods (like for example coredns) fails to start because crio does not find the `loopback` CNI plugin, which is in `containers-basic`.

**Comment by bryteise** [comment]
@pohly Ah thanks for pointing out that tutorial, it is definitely going to need to change as @mcastelino  works through making our k8s more functional out of the box.

**Comment by mythi** [comment]
I'm OK with the setup rnow. Closing.
