### ISSUE TITLE
chrome-gnome-shell integration

### ISSUE THREAD

**Issue by ByteEnable** [clearlinux/distribution#258]
Unable to install gnome-shell extensions from https://extensions.gnome.org/ because the native host connector is not detected.

**Describe the solution you'd like**
I would like to be able to install Gnome shell extensions from https://extensions.gnome.org/

**Describe alternatives you've considered**
I have manually installed an extension to ~./local but that does not appear to work.  I have to install in /usr/share as root.

**Comment by miguelinux** [comment]
Have you tried with "Gnome Software", it should work.

Are you behind a proxy?

**Comment by ByteEnable** [comment]
Yes behind a proxy at work.

**Comment by ByteEnable** [comment]
I was able to manually install an extension.  Locally.  So that is functional.  However, is it possible to have the connector?

**Comment by ser** [comment]
Gnome extensions via Gnome software is crap as it shows many outdated and non compatible extensions.

Can we have connector ready please?

**Comment by ahkok** [comment]
We can't. We ship the official firefox without custom addons.

You can install it yourself:

https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/

**Comment by ahkok** [comment]
@mrkz 

Can we add: 

https://gitlab.gnome.org/GNOME/chrome-gnome-shell/-/archive/v10.1/chrome-gnome-shell-v10.1.tar.bz2

**Comment by gregor160300** [comment]
I see the package already exists on the clearlinux-pkgs GitHub, but why hasn't this been added to a bundle yet?

**Comment by lebensterben** [comment]
>I see the package already exists on the clearlinux-pkgs GitHub, but why hasn't this been added to a bundle yet?

@gregor160300 I built it from source but it still doesn't work.

**Comment by gregor160300** [comment]
> 
> >I see the package already exists on the clearlinux-pkgs GitHub, but why hasn't this been added to a bundle yet?
> 
> @gregor160300 I built it from source but it still doesn't work.

Hmm I didn't test it on my machine yet, might try it tonight, I do think that it is something we need natively as 3rd party is too limited at this moment

**Comment by gregor160300** [comment]
> 
> >I see the package already exists on the clearlinux-pkgs GitHub, but why hasn't this been added to a bundle yet?
> 
> @gregor160300 I built it from source but it still doesn't work.

Hmm I didn't test it on my machine yet, might try it tonight, I do think that it is something we need natively as 3rd party is too limited at this moment

**Comment by kunihir0** [comment]
not working out of the box 2 years after the opening of this. I thought it would work out of the box since the Dev team on the OS is mainly focus on the gnome desktop environment but having the extensions not working is a turn off a bit lol just a minor inconvenience to me but I would really love to have this fixed within the year i hope.

"Although GNOME Shell integration extension is running, native host connector is not detected. Refer for instructions about installing connector."

Clear Linux OS; Build ID: 36270

reproduce error:
fresh install -> wait for auto update, do not touch any applications just wait -> reboot -> login -> open firefox -> in gnome-extensions -> reload firefox -> go to the gnome extensions website -> error message in red

**Comment by nobodyatandnothing** [comment]
duplicate of https://github.com/clearlinux/distribution/issues/406
