### ISSUE TITLE
Allow to set system variables and/or ping programmatically

### ISSUE THREAD

**Issue by dvska** [clearlinux/distribution#263]
**Is your feature request related to a problem? Please describe.**
We need to **ping** some hosts programmatically, Python3 code gives
```
    s = _socket.socket(_socket.AF_INET, _socket.SOCK_DGRAM, _socket.IPPROTO_ICMP)
  File "/conda/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
```

Tried to set
```
sysctl -w net.ipv4.ping_group_range="0 65536"
```

```
sysctl: setting key "net.ipv4.ping_group_range": Read-only file system
```

**Describe the solution you'd like**
Any solution to **ping** programmatically.

**Comment by fenrus75** [comment]
eh maybe asking the obvious but... ICMP is normally a privileged thing.. are you trying this as root?

also a thing to try is use our system python rather than something else; the something else might be playing sandboxing tricks after all

**Comment by dvska** [comment]
Arjan, thanks for replying.

Ok, these was experiments from https://hub.docker.com/r/red8012/fastconda/~/dockerfile/ docker image. I will try it at stock Clear Linux, after #264 fixed.

**Comment by puneetse** [comment]
You can't modify sysctl values when inside the container by design. You can set it at runtime however using the `docker run` command with the `--sysctl` switch. See here for more details: https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime .

I tried it with the container you linked and it seemed to work.

I'm not sure on your use case, but have you considered something that simply leverages the `ping` program? The `ping` program provides the suid permission bits already to avoid having to deal with the raw socket permission issue you're seeing.

**Comment by ahkok** [comment]
I'm considering this a "works as intended" type thing. There are several solutions available, and it's unlikely that the requested change is the one we would actually implement due to the listed concerns.
