### ISSUE TITLE
Build htop with libsensors

### ISSUE THREAD

**Issue by KaeLL** [clearlinux/distribution#2681]
Title. Would like to have my CPU temps displayed within HTOP.

**Comment by WSLUser** [comment]
Would want libsensors to be an optional dependency if added or make a separate bundle with it enabled.

**Comment by KaeLL** [comment]
@WSLUser How would the former be achieved?

**Comment by WSLUser** [comment]
Initial thought was if the library wasn't installed, it would silently be allowed to fail to load in htop and wouldn't display it. Would require ensuring htop has logic configured to ensure it didn't just fail to run due to missing this particular library. They do custom patches all the time so this is feasible. But it's probably easier to just make a separate bundle. My only concern with making libsensors the default is I run Clear Linux in a virtualized environment that doesn't have the physical access needed for the thermal drivers in kernel to work. So I always try ensuring only the bare minimum thermal config options are enabled in kernel (ideally they would all be disabled but the kernel refuses to allow this during compilation). This obviously has an impact on libsensors and could cause issues. So I want to ensure I can use the known stable htop without any problems.

**Comment by fenrus75** [comment]
with htop in our smallest setups, i'm worried about this one.

pulling in libsensors itself is not nice for size. the libsensors in turn
pulls in other stuff and it cascades out of hand pretty quickly that way to
get an enormous amount of "bloat" in the smaller installs

**Comment by KaeLL** [comment]
True, which is why, in my noob opinion, having a separate bundle seems like the way to go.

**Comment by fenrus75** [comment]
the name of the binary would then be something not-htop.... not so sure
that's all that useful ;(

**Comment by KaeLL** [comment]
From the wording in htop's [readme](https://github.com/htop-dev/htop#linux), I reckon the lib's absence at runtime is accounted for, but I'm not sure.
Truth is I don't know which of the options presented by WSLUser is the best here. I only meant to start the discussion.
As for the name in case the new bundle option were to be selected, maybe htop-sensors, htop-opt (in anticipation of other optional being enabled one day), I don't know. Personally, I'd most likely alias it, so I don't mind.

**Comment by bryteise** [comment]
I recently added https://github.com/aristocratos/btop which is a more full featured thing, maybe use that instead?

**Comment by bwarden** [comment]
I've enabled sensors support in this commit (will be published here once it's in a release):
https://github.com/clearlinux-pkgs/htop/commit/3ed12583defbcd65fdcf4820188a06121b413218

This adds about 20 kB to the size of `/usr/bin/htop`.

The package doesn't depend on lm-sensors, so it won't pull it into the `htop` bundle, but if you already have libsensors.so (provided by several other bundles, but minimally by the `lm-sensors` bundle), it will automatically use it at runtime. You'll have to enable CPU temperature in the display options, of course.

**Comment by KaeLL** [comment]
Feel free to closed the issue as solved now.
Btw @bryteise it would be nice if btop showed core clocks like htop.
