### ISSUE TITLE
Package hardinfo

### ISSUE THREAD

**Issue by lpereira** [clearlinux/distribution#270]
**Describe the solution you'd like**
Hardinfo is a tool to profile the system (hardware, software, network) and perform simple benchmarks.  It's also possible to generate reports in HTML.

It would be nice if it were packaged in Clear Linux.  It's available in most distributions already.  It hasn't been released in a while, but if there's such interest, I can tag a preliminary version.

[Git repository](https://github.com/lpereira/hardinfo)

**Additional context**
![Generate reports](https://i.imgur.com/r6XWYJv.png)
![System summary](https://i.imgur.com/UYNQJog.png)
![OS info](https://i.imgur.com/6my0Bnm.png)

**Comment by ahkok** [comment]
Send patch. Will accept. Definitely add newer than 2009 tags for releases, though!

**Comment by ahkok** [comment]
Is this only gtk2 though? Can you brush it up a version?

**Comment by lpereira** [comment]
If built with `-DHARDINFO_GTK3`, it should work with newer GTK+ versions.  It's not the default yet because there are some issues with it still.

**Comment by jurobystricky** [comment]
Any progress on this one?
I built it with 
https://github.com/lpereira/hardinfo/archive/098e0c0955305ae60cf8b8892bcf34a957f5286c.tar.gz

(The last tagged release 0.5.1 is 10 years old,  so I used the latest master.)

Also in CMakeLists.txt I ensured:
<pre>
option(HARDINFO_GTK3 "Attempt to build for GTK3 (0/off for GTK2)" 1)
</pre>

It builds fine (using autospec), but when trying to run it I get this:

<pre>

$ sudo hardinfo -f html

*** Error: No module could be loaded. Check permissions on "/usr/usr/lib64/hardinfo" and try again.

Trace/breakpoint trap (core dumped)
</pre>

Two issues there (probably related): weird path and an embedded breakpoint.  But maybe I am missing something.

**Comment by lpereira** [comment]
Thanks for looking at this, @jurobystricky.  The GTK3 version requires a lot of work still; I wouldn't recommend using it.  The "/usr/usr" thing is definitely a bug in the build system, though.

**Comment by sunnyflunk** [comment]
The issue seems to be here: https://github.com/lpereira/hardinfo/blob/835d55097688bbb0a8f236459db759108b7af7c7/config.h.cmake#L14

By default I think `CMAKE_INSTALL_LIBDIR` is set to `/usr/lib64` where it is expecting it to be `lib64`.

Try adding `-DCMAKE_INSTALL_LIBDIR=lib64` to `cmake_args` to see if that helps.

**Comment by jurobystricky** [comment]
Yes, that helped a lot. The program now runs nicely (with GTK3). However, I needed to launch it from cmd line, as it did not show up on desktop and activities did not find it either. But that may be due to GTK3, I will rebuild with GTK2. Otherwise, I only tested it by clicking/viewing various info blocks. Looks very nice. Launching from terminal I see some GTK/GLIB warnings/assertions on the terminal. Again, this could be related to GTK3.

**Comment by jurobystricky** [comment]
I rebuilt it again for GTK2. No problems. "Activities" found it, alas not as "hardinfo" but as "System Profiler and Benchmark" (may have been found using GTK3 as well, but I was looking "hardinfo", so may bad).
Looks fine ( actually very nice), seems to work fine as well. I'll play with it a bit and then send the patch to the mailing list for a review.

**Comment by ahkok** [comment]
I'd prefer the gtk3 version TBH!

**Comment by lpereira** [comment]
Patches to improve the GTK3 version are appreciated. Right now it's barely
usable.
