### ISSUE TITLE
sshuttle utility

### ISSUE THREAD

**Issue by cyberpika2** [clearlinux/distribution#2742]
Official package name:
sshuttle

License (must be an OSI approved Open Source license):
[LGPL-2.1](https://github.com/sshuttle/sshuttle/commit/8ee230bca7b8ff4322789149e60866246bc4dd48)
Download URL of latest release:
https://github.com/sshuttle/sshuttle/archive/refs/tags/v1.1.1.tar.gz

Latest release date (must be recent):
20220805

Description:
sshuttle: where transparent proxy meets VPN meets ssh

As far as I know, sshuttle is the only program that solves the following common case:

    Your client machine (or router) is Linux, FreeBSD, or MacOS.
    You have access to a remote network via ssh.
    You don't necessarily have admin access on the remote network.
    The remote network has no VPN, or only stupid/complex VPN protocols (IPsec, PPTP, etc). Or maybe you are the admin and you just got frustrated with the awful state of VPN tools.
    You don't want to create an ssh port forward for every single host/port on the remote network.
    You hate openssh's port forwarding because it's randomly slow and/or stupid.
    You can't use openssh's PermitTunnel feature because it's disabled by default on openssh servers; plus it does TCP-over-TCP, which has [terrible performance](https://sshuttle.readthedocs.io/en/stable/how-it-works.html).

Please and thank you!

**Comment by thiagomacieira** [comment]
Please note that TCP/IP-over-TCP/IP is usually a bad idea due to packet retransmissions over a reliable channel. If your connection is slightly bad and you start to drop packets, both TCP layers will retransmit, so the lower layer will see an increase in number of packets it must deliver.

This might be a good stopgap solution if you really need it, but it's not a replacement for a proper VPN over UDP (like OpenVPN and OpenConnect) or directly over IP (IPSec). You may even want to try SSH's built-in ability to start a SOCKS server with the -D option before you try VPN.

**Comment by bwarden** [comment]
Available in releases >=37630 as bundle `sshuttle`.
