### ISSUE TITLE
X.org not working

### ISSUE THREAD

**Issue by ilmarn** [clearlinux/distribution#2817]
Starting from version 380XX (and maybe earlier, haven't tried for some time) and latest 38140 X not working on amdgpu

(EE) Failed to load /usr/lib64/xorg/modules/drivers/amdgpu_drv.so: /usr/lib64/xorg/modules/drivers/amdgpu_drv.so: undefined symbol: amdgpu_pixmap_index

full log
[Xorg.0.log](https://github.com/clearlinux/distribution/files/10507212/Xorg.0.log)

**Comment by fenrus75** [comment]
Hmm I thought we had fixed this

but also please consider using wayland; both the xorg server and amdgpu
xf86 driver have been effectively unmaintained upstream

[Standard note: Because the world has moved to Wayland and the Xorg world
is barely maintained, we are phasing out Xorg support in the distro, by
first no longer installing Xorg automatically anymore, and much later,
removing it entirely. We will try to keep it working as long as reasonable
but it's not something we're going to spend disproportionate resources on]

**Comment by ilmarn** [comment]
totally agree. was using wayland for some time already but after gnome 42 update (1st clear linux release with gnome 42 was fine but next brought ui glitches) wayland/gnome became quite unusable for me. desktop and all apps have redraw problems (mutter/mesa issue?), feeling like current and previous draw frames have mixed up indexes. new frame drawn but previous frame shown, hard to decribe

need to check KDE. in windows all is fine
