### ISSUE TITLE
 sudo swupd bundle-remove rust-basic fails to remove files

### ISSUE THREAD

**Issue by russeree** [clearlinux/distribution#2866]
The rust-basic package doesn't actually uninstall rustc,cargo, etc... when the remove command is used. This leads to the event where it's difficult to install a different version of rust.

![image](https://user-images.githubusercontent.com/3104223/229401906-59291ea2-1181-4d46-a109-ef8e8259b9af.png)

**Comment by fenrus75** [comment]
The rust compiler is present in roughly 10 bundles... I don't know which of those 10 you also have... but bundles aren't "packages"; components can be (and are) present in multiple bundles.

Also I assume you're installing your own rust components into /opt or /usr/local (since swupd "owns" all of /usr except /usr/local and will manage the content of that based on which bundles are installed)

**Comment by russeree** [comment]
Other than a fresh install rust-basic was the only swupd package I had installed. I am going to replicate this on a fresh install. Another user was having trouble with this on Reddit too.
https://www.reddit.com/r/ClearLinux/comments/qox9gv/comment/hjs5jws/

The reason why this became a problem for me is that the rust analyzer in VS Code does not play well expanding macros using the 1.67.1 version.
