### ISSUE TITLE
Problems switching between wired and wireless interfaces

### ISSUE THREAD

**Issue by jfstroman** [clearlinux/distribution#289]
**Describe the bug**

Disabling the wired network via the control panel seems to be a one-way process. 

After enabling WiFi and disabling wired, I was unable to reverse the process (disabling WiFi and re-enabling the wired network) without having to reboot.

Also notable is that disabling one wired interface seems to break them both (I was not able to unplug the network cable from one port and get it working on the other one).

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by busykai** [comment]
New installations will now use NetworkManager to manage all the interfaces. For existing installations `man stateless` contains the node on how to switch from `systemd-networkd` to `NetworkManager` for all the network interfaces.

**Comment by lebensterben** [comment]
> New installations will now use NetworkManager to manage all the interfaces. For existing installations `man stateless` contains the node on how to switch from `systemd-networkd` to `NetworkManager` for all the network interfaces.

1. There's weird bug maybe related to the switch. I only have wired Ethernet connection and it's not managed. After a certain system update during last week, `gnome-software` shows an error like it cannot update because there's no internet connection. This persists even after reboot.<br>
I just followed the instructions in the `man stateless` and the problem is fixed. So please consider to apply this change to all existing systems.

2. As for the instruction it self, the line 
`sudo systemctl disable systemd-networkd sudo systemctl stop systemd-networkd` 
shall be changed to 
`sudo systemctl disable systemd-networkd && sudo systemctl stop systemd-networkd`.
