### ISSUE TITLE
Adding iDRAC Service Module bundle

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#299]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was hoping that Dell's iDRAC Service Module could be made available via a bundle.

**Describe alternatives you've considered**
I could install from scratch, but having this managed in Clear Linux's `swupd` ecosystem would be far more convenient.

**Additional context**
iDRAC is a system that allows for "lights out" management of a Dell server. It allows you to power a machine on and off, view and control the server throughout the POST of the system, as well as measure a variety of metrics. Building on iDRAC, the iDRAC Service Module is an agent that lives on the host operating system and improve its functionality.

More information can be found in https://www.dell.com/support/contents/us/en/04/article/product-support/self-support-knowledgebase/enterprise-resource-center/systemsmanagement/eism

**Comment by thiagomacieira** [comment]
I don't think we can. First, I can't find the sources for this tool. Second, the license agreements that I can find have the word "nontransferable" in them. I am not a lawyer, so I am not interpreting them, but this non-OSI-approved licence could be a problem.

Conclusion: I don't think Clear Linux can carry this package because it's not open source and doesn't seem like Dell wants us to.
