### ISSUE TITLE
Illegal instruction (core dumped) while build mesa 24.0+1977 package on Xeon 2680V2

### ISSUE THREAD

**Issue by inferrna** [clearlinux/distribution#3062]
Release `40830`

I'm trying to build a custom [mesa](https://github.com/clearlinux-pkgs/mesa) package of version `24.0+1977` and got `Illegal instruction (core dumped)` error somewhere inside mock environment where I have no access.
Fortunately, there was a [build.log](https://github.com/clearlinux/distribution/files/14472625/build.log) in the `results` directory

Currently, I'm on `24.0+1057` which I successfully built by this way.

**Comment by volkertb** [comment]
This Xeon CPU is of the Ivy Bridge generation. I just reported [another `Illegal instruction` error when running `swupd search whatever`](https://github.com/clearlinux/distribution/issues/3063) on a Sandy Bridge system.

It would appear that recent updates of Clear Linux OS broke compatibility with older (`x86-64-v2`) CPUs.

But I ran the [Clear Linux OS compatibility check script ](https://www.clearlinux.org/clear-linux-documentation/get-started/compatibility-check.html#compatibility-check)and it verified that the system on which I encountered the problem is still compatible with Clear Linux OS and should still be capable of running it. I know there has been talk among many Linux distros about possibly dropping support for CPUs that don't support at least `x86-64-v3` (which would be any CPU generation older than Haswell, including Sandy Bridge and Ivy Bridge), but it doesn't appear that Clear Linux OS developers have already announced such a step, much less deliberately taken it. Something like that should definitely be announced well in advance, to allow users to either upgrade their hardware or move to other distros.

My suspicion is that the CI/CD pipelines and build systems for Clear Linux OS aren't actively checking whether any new builds are still compatible with `x86-64-v2` CPUs, and such incompatibility inadvertently crept into some packages of the distro. But it's crazy that it would even break something as fundamental as `swupd`.

**Comment by fenrus75** [comment]
we had a misbruikt in Python (found and fixed now)

swupd search actually is a Python program


if you want go to the pending update do

swupd update --format staging

**Comment by fenrus75** [comment]
and yes our intent definitely is to keep supporting v2 hardware

(as a result of this we've added several more ci steps on Friday... this
escaped in a new and exciting way)

**Comment by volkertb** [comment]
> we had a **misbruikt** in Python (found and fixed now)

Ah, een verkeerd ingestelde autocorrect, ik vind dat ook altijd zo vervelend wanneer dat gebeurt op mijn telefoon. :sweat_smile:

Anyway, I just ran `swupd update --format staging`, as you suggested, and I can confirm that `swupd search whatever` is no longer failing with an `Illegal instruction`. So it fixes issue #3063, at least.

By the way, audio also stopped working on my Clear Linux system after a recent update. The only Output Device being shown in GNOME Volume Control is the Dummy Output. No hardware devices, even though the command `lspci -nnk | grep -A2 Audio` is showing two detected audio devices, both using the `snd_hda_intel` driver.

Let's see if the `swupd update --format staging` command also fixed that after a reboot. (Without a reboot, it's still not working after that update.)

**Comment by fenrus75** [comment]
woops yeah multilanguage keyboard + bad autocorrect ;(

for the audio issue might need to file a new ticket (to not make this one
messy with multiple things)... but first check in dmesg if any obvious
errors are there

we haven't really touched anything audio drivers/setup lately so it must be
something odd in a kernel security update or something

**Comment by volkertb** [comment]
Thanks. I'll open another ticket for that if I can't get it to work. However, one thing I noticed is `pavucontrol` ("PulseAudio Volume Control") crashing with invalid opcodes whenever I try to adjust the volume slider in the `Output Devices` tab, which might also imply a compatibility breakage with older CPUs:

Relevant snippet from `dmesg`:

```text
[ 3376.296544] pavucontrol[64752]: segfault at 0 ip 0000000000000000 sp 00007ffd79eb4a68 error 14 cpu 0 likely on CPU 0 (core 0, socket 0)
[ 3376.296559] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[ 3382.930912] pavucontrol[92043]: segfault at 0 ip 0000000000000000 sp 00007fffde34dc58 error 14 cpu 3 likely on CPU 3 (core 1, socket 0)
[ 3382.930931] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[ 3392.003943] pavucontrol[92067]: segfault at 0 ip 0000000000000000 sp 00007ffd4b515868 error 14 cpu 0 likely on CPU 0 (core 0, socket 0)
[ 3392.003961] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[ 3434.229916] pavucontrol[92134]: segfault at 0 ip 0000000000000000 sp 00007ffc22228ed8 error 14 cpu 0 likely on CPU 0 (core 0, socket 0)
[ 3434.229934] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[ 3437.334946] pavucontrol[92161]: segfault at 0 ip 0000000000000000 sp 00007ffd393dd1c8 error 14 cpu 2 likely on CPU 2 (core 0, socket 0)
[ 3437.334965] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[ 3585.165024] pavucontrol[92182]: segfault at 0 ip 0000000000000000 sp 00007fff190b4278 error 14 cpu 0 likely on CPU 0 (core 0, socket 0)
[ 3585.165043] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
```

I'll close the other issue with your solution, but keep this one open until @inferrna or others have confirmed that the suggested staging update fixed this issue as well.

Thanks!

**Comment by fenrus75** [comment]
btw out of curiosity -- what would you be changing in the mesa rebuild? Is
there something we should improve in our package ?

**Comment by inferrna** [comment]
The main reason I do it is to enable Gallium Nine package (in some cases it better than proton, also I have an old laptop on r600 GPU).
Additionally, I found ability to change `video-codecs` from `all_free` to `all`.

**Comment by inferrna** [comment]
Got success with python from 41170
