### ISSUE TITLE
WineGUI update

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3178]
@fenrus75: Many thanks for porting WineGUI to CL! You, however, grabbed a very old version (1.0.0.0). Please [head over here and download the latest](https://gitlab.melroy.org/melroy/winegui/-/archive/v2.6.1/winegui-v2.6.1.tar.gz). Many thanks!

**Comment by K1ngfish3r** [comment]
it's 2.6.1 no?
https://github.com/clearlinux-pkgs/winegui/blob/8e3c7548aeaea11040caa4342df2c06cee786b83/Makefile#L2

**Comment by Aqua1ung** [comment]
> it's 2.6.1 no?

Yes, the newest is 2.6.1. Yet `sudo swupd bundle-add winegui` installs this:

![Screenshot from 2024-09-02 14-31-43](https://github.com/user-attachments/assets/c310d662-ef98-439f-a835-7c9c7bb0b42c)

![Screenshot from 2024-09-02 14-29-14](https://github.com/user-attachments/assets/fb850377-8cf7-49f4-a834-83be45298bc4)

**Comment by K1ngfish3r** [comment]
![image](https://github.com/user-attachments/assets/bddec815-0fe8-4e2c-90b1-a0a93df52ce3)
seems to be reporting itself as 1.0.0
hmm

**Comment by fenrus75** [comment]
we should have 2.6.1 .. not sure why it thinks it's 1.0 though

**Comment by melroy89** [comment]
No problem, I found the issue. The version from WineGUI is determined from git tags. So the CI/CD pipeline is fully automated when creating a new release.

The best way to build from source is to use the following tar.gz instead: https://winegui.melroy.org/downloads/WineGUI-Source-v2.6.1.tar.gz

See also the WineGUI AUR package (I maintain as well): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=winegui

The only difference between the previously mentioned tar.gz file and git source is that the this tar.gz file is build during CI/CD to include a `version.txt` file, which is used by CMake to build the code and include the version.

This link is also part of the [release assets](https://gitlab.melroy.org/melroy/winegui/-/releases):

![image](https://github.com/user-attachments/assets/e37181d6-349c-4611-a80e-8cf7ccb91d29)

Too bad I can't disable the GitLab generated tar.gz files, since those tar.gz files are created _before_ CI/CD runs.  Anyhow, just use: https://winegui.melroy.org/downloads/WineGUI-Source-v2.6.1.tar.gz

**Comment by fenrus75** [comment]
I'll switch the tarbals -- is that download url going to have future
releases as well?
(because then our automation is likely to pick them up)

**Comment by melroy89** [comment]
> I'll switch the tarbals -- is that download url going to have future releases as well? (because then our automation is likely to pick them up)

If you mean that the new tar.gz versions will be released at: https://winegui.melroy.org/downloads/. Then the answer is yes (again use `WineGUI-Source-....tar.gz`). 

If you want to know the latest release, I also automatically update: https://winegui.melroy.org/latest_release.txt

**Comment by fenrus75** [comment]
I indeed meant the /downloads/ url -- we have tooling that monitors for new
releases (and then notifies us) -- this helps us keep on top of new
software...

thanks for the help!

**Comment by melroy89** [comment]
I saw that the spec file is updated in commit: https://github.com/clearlinux-pkgs/winegui/commit/93443844e69e54acb9a119b17e85b001e27e6bd5. That seems all good!

I only see build dependencies (like `gtkmm-3.0`).. Be sure to include several important run-time dependencies also, so people have the best possible first-time experience. Here an Debian example, but you get the drill: https://gitlab.melroy.org/melroy/winegui/-/blob/main/cmake/packaging.cmake?ref_type=heads#L41

`cabextract`, `wget`, `unzip`, `p7zip` etc. are needed by other tools like Winetricks and when there are additional DDLs overrides are installed, etc. etc. This is needed when people start interacting with WineGUI and you want to avoid having people complain about missing dependencies at runtime or getting errors.

**Comment by fenrus75** [comment]
I added cabextract to our bundle definition earlier -- just adding wget
unzip and p7zip now

**Comment by melroy89** [comment]
Great! In that case, I believe this ticket can be closed. Unless there are any more questions or issues.
