### ISSUE TITLE
clear-kvm: error message and incorrect "kernel update"

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#32]
When booting into clear-21530-kvm.img.xz for the first time, I get:
```
Error opening output file '/run/log/bootchart-20180328-1437.svg': No such file or directory

Clear Linux OS for Intel Architecture clr-919330ae8b5540cc81075b850ebefa71 ttyS0
clr-919330ae8b5540cc81075b850ebefa71 login: root
You are required to change your password immediately (administrator enforced)
New password: 
Retype new password: 
 * A kernel update is available: you may wish to reboot the system.
```

Both the "Error opening" and the "A kernel update" message probably shouldn't be shown. Not a big issue, just cosmetic?

**Comment by ahkok** [comment]
The first one (bootchart) is somewhat serious, since that error indicates that `/run/log` isn't created fast enough in time. It's a significant error, but fixing would be potentially complex, since essentially the bootchart program is running too short for your VM.

The second message comes from the `motd` that gets autogenerated. No idea yet why it was created, but I'll look into it.

**Comment by ahkok** [comment]
Spotted the culprit of the kernel update message.

clr-boot-manager-2.0.0-28 Should fix that problem.

I'm closing this for now. We can reopen the systemd-bootchart one later separately if it bothers people too much :).
