### ISSUE TITLE
yum install will overwrite /lib/os-release file

### ISSUE THREAD

**Issue by yongfengdu** [clearlinux/distribution#323]
I know that yum is not recommended way to install packages, but for our develop environment, we need to use yum for package install to avoid add too huge bundles.

Steps to reproduce:
1. swupd bundle-add package-builder   # This is to install yum
2. edit /etc/yum.conf file, I'm using an internal repo
3. yum install wget
Then the /lib/os-release will be overwritten, and the OS_VERSION is back to 1.

# swupd info
Installed version: 1
# ls -l /lib/os-release
-rw-r--r-- 1 root root 303 Jan 13  2017 /lib/os-release    # Time Stamp is 2017

The following swupd bundle-add command will fail
# swupd bundle-add vim
Error: Loaded incompatible manifest last change
Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
Error: Loaded incompatible manifest last change
Failed to load 1 MoM manifest
Cannot load official manifest MoM for version 1

Not sure if this is a bug, report this as low priority.

**Comment by fenrus75** [comment]
Well yes yum does not work......

**Comment by ahkok** [comment]
> Then the /lib/os-release will be overwritten, and the OS_VERSION is back to 1.

Does the `yum` command do this?

**Comment by ahkok** [comment]
No matter what, this is not a bug in Clear Linux.

If you need different bundles, please feel free to open a ticket asking for specific, smaller bundles and we can discuss and implement them if they are reasonable.

**Comment by phmccarty** [comment]
Just to clarify the situation:

The overwriting of /usr/lib/os-release when using yum or dnf *is* expected, because the `filesystem` package installs that file, and it contains `VERSION_ID=1`.

The reason why VERSION_ID normally lists the Clear Linux version is because mixer overwrites the file during the Clear Linux build process, effectively replacing version `1` with `26700`, or whatever the currently building version is.
