### ISSUE TITLE
Strange NTP setup behaviour ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#384]
Automatic Date & Time / Time zone (NTP) setup didn't work automatically.

1.  Change "Date&Time / Time zone" to automatic
2. => didn't change the time immediately
3. Reboot CLR (the VM, see below)
4. => didn't change the time still
5. Perform a real "PowerOff" and start CLR (the VM)
6. => now the date seems to have been properly set (zone slightly incorrect but that's ok)

Date & Time / Time zone should be automatically set, either instantly (few seconds/minutes ?),
or at least after a (warm) reboot.

 - Version :
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27420
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles :
acpica-unix2 alsa-utils bootloader c-basic cloud-api cloud-control clr-installer containers-basic cryptography curl darktable desktop desktop-apps desktop-assets desktop-autostart desktop-gnomelibs desktop-locales diffutils dosfstools editors emacs ethtool file findutils firefox fuse fwupdate gdb git go-basic gzip htop iproute2 irssi java-basic joe kbd kernel-install kernel-lts kernel-native kvm-host less libX11client libva-utils llvm locales make meld nasm network-basic nfs-utils openssh-server openssl os-core os-core-update os-core-webproxy os-utils-gui p11-kit parallel patch perl-basic pmdk powertop python3-basic smartmontools storage-utils strace sudo sysadmin-basic telemetrics thunderbird tmux tzdata unzip valgrind vim weechat which wpa_supplicant x11-server xemacs xfce4-desktop xfsprogs xz znc zstd 

Note that I'm running CLR as guest in VirtualBox, on Windows 10 corporate laptop host,
and using native kernel 4.20.5-488 (because with the LTS kernel (that must be activating the guest additions,.) I have some severe limitations (graphical screen blank after restoring state..))

**Comment by ahkok** [comment]
clear uses systemd-timesyncd. This may be an upstream bug.

**Comment by bwarden** [comment]
> CLR as guest in VirtualBox

More likely a problem with VirtualBox Guest Additions.

**Comment by nsauzede** [comment]
Hmmm.. not sure...
I'm in fact NOT using LTS kernel, because had graphical issues with it (see my edits in the description above)

**Comment by tpleavitt** [comment]
@nsauzede , can you confirm this with the LTS kernel.  Currently the LTS is required for the guest additions to function correctly

**Comment by nsauzede** [comment]
Which LTS version should I use ?
Currently at boot the menu offers : 
lts2018-4.19.28-9
lts2018-4.19.29-12
lts-4.19.27.436
(in that order)

**Comment by nsauzede** [comment]
Are you sure that the guest additions (and hence, the LTS kernel) is needed for the ntp sync to work ?
I'm using the NATIVE kernel for a while now and the clock seems to be correct (did not really try to fool it up to test, though)
BTW, what advantages do the guest additions bring vs. using NATIVE kernel ?
EG: I never could make the "shared clipboard" work, nor the virtual FileSystem..

**Comment by tpleavitt** [comment]
The latest version of the LTS.  @bwarden is in the process of adding the shared clipboard work and I'll let him comment on your other questions

**Comment by bwarden** [comment]
Use the (latest) lts2018 kernel for VirtualBox now. The plain lts kernel is deprecated, and the kernel-lts bundle now provides the lts2018 kernel instead.

Time sync in guest VMs is kind of special. Since the VM only executes when the host decides to, the normal software clock is pretty unreliable. NTP software doesn't work well because it expects the clock not to jump around significantly during normal operation. You may not notice this when the guest is running, but will see a huge lag before updating e.g. after pausing the guest. Client-side VM drivers work around this by providing their own time sync from the host clock in a kernel driver, essentially letting the host explicitly set the software clock to the correct time whenever necessary. This also takes care of immediately rolling the clock forward upon resuming the guest, and other scenarios. Some of them handle updating the guest clock after host suspend/resume, too.

You can see VBox guest drivers do this by manually setting the clock to a time in the past and checking the kernel messages:
```
$ sudo date -s @$(($(date +%s) - 86400)); sleep 5; date; dmesg | grep timesync
Mon 18 Mar 2019 02:35:56 PM PDT
Tue 19 Mar 2019 02:36:01 PM PDT
[ 2323.754370] 21:35:58.734044 timesync vgsvcTimeSyncWorker: Radical guest time change: -86 390 911 328 000ns (GuestNow=1 552 944 957 822 468 000 ns GuestLast=1 553 031 348 733 796 000 ns fSetTimeLastLoop=false)
```

I figured out why the shared clipboard and related services weren't working and I expect to push the fix in the next couple of days. I tested clipboard and file drag/drop so far. I haven't tested shared folders yet.

**Comment by nsauzede** [comment]
@bwarden awesome news if the shared clipboard can work ! I'm really missing this vs. my old Ubuntu18.10 VM
I'd say the shared folders is less important, as it seems quite unreliable also with Ubuntu VM..
I can work around this with fidh/scp transfers etc...
Didn't know this background around NTP vs. VM - thx
Will try to stick to LTS2018 (4.19.29-12 for now) and will report if I face NTP issues again..

**Comment by bwarden** [comment]
File drag-and-drop may be a helpful substitute for shared folders, too. It copies the dragged file to a path under /tmp and pastes the final location to the app where you dragged it, so pretty handy in a terminal, for example.

**Comment by tpleavitt** [comment]
@nsauzede , I'm going to close this issue and if you have any problems associated with this, please reopen.
