### ISSUE TITLE
Need a cd dvd utility 

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/distribution#4]
I need a cd/dvd utility like k3b, when trying to build k3b i find that most of the dependencies are from 2008-2005 and very hard to build, its will be really good if there will be a cd/dvd utility provided

**Comment by ahkok** [comment]
Please describe the functionality you need from "cd/dvd utility". Do you need to read UFS DVD filesystems? Or play audio CDs? or burn data DVDs?

**Comment by tuxutku** [comment]
I need to make k3b working for both cd and dvd, not including double layer dvd or blueray, i need to be able to rip audio and video cd and video dvd, also i need to be able to burn bootable disks, i allready installed cdrkit but not dvdauthor, i can read cd file system but not tested dvd yet

**Comment by ahkok** [comment]
> i need to be able to rip audio and video cd and video dvd

This is currently not a supported functionality, nor will it be

> be able to burn bootable disks

Bootable USB media have entirely replaced the need for optical media. This would be an ineffective use of our time.

You might get far using `xfburn` by the way, since most of the xfce4 stack is already packaged in the `xfce4-desktop`. You'll need to grab `libisofs` and `libburn` from https://dev.lovelyhq.com/libburnia/web/wikis/Releases and then xfburn from http://goodies.xfce.org/projects/applications/xfburn

**Comment by ahkok** [comment]
I will add `xfburn` to the `xfce4-desktop` bundle since it's trivial enough and a good basic start point. It should integrate reasonably with the gnome desktop as well, so hopefully that suits your needs.

**Comment by ahkok** [comment]
Added xfburn. It will be in a future release, probably in a day or two. You'll need the `xfce4-desktop` bundle.
