### ISSUE TITLE
MariaDB 10.3 with MyRocks storage engine.

### ISSUE THREAD

**Issue by pixelblender** [clearlinux/distribution#416]
Hi,

Is it possible to have MariaDB 10.3 with "MyRocks storage engine" plugin?

**Comment by phmccarty** [comment]
@pixelblender - I actually see the rocksdb plugin being installed by the mariadb package. It is named:

```
/usr/lib64/mysql/plugin/ha_rocksdb.so
```

Is that plugin usable? I haven't tried testing it myself?

**Comment by phmccarty** [comment]
Still haven't tested this, but according to the documentation, I think we provide the required plugin already. Please reopen if you still see the issue.

**Comment by zardoz-bzar** [comment]
Plugins get loaded the way other things do. Mysql/Maria get all cute:
[mariadb]
plugin_load_add = ha_rocksdb

When you do this, it loads rocksdb (which, with all the optimized compression libs in clear, really does rock).

But wait, there is also a ha_rocksdb_avx2 in the plugins dir. This isn't ldd. This is MariaDB.

To load a plugin with a specific SONAME, you have to use SQL.

mysql -uroot -p[redacted] -e "INSTALL PLUGIN ha_rocksdb SONAME 'ha_rocksdb.so.avx2';"

Since rocksdb is all about memory and compression, match made in heaven?
ERROR 1126 (HY000) at line 1: Can't open shared library '/usr/lib64/mysql/plugin/ha_rocksdb.so.avx2.so' (errno: 2, cannot open shared object file: No such file or directory)

The mariadb parser assumes the user is an idiot, and autocorrects them wrongly. 

workaround:
ln -s /usr/lib64/mysql/plugin/ha_rocksdb.so.avx2 /usr/lib64/mysql/plugin/ha_rocksdb.so.avx2.so

run:
mysql -uroot -pkilroy -e "SHOW PLUGINS;"  | grep ROCK

Hey, we're in business.

And for anyone who finds this via google searches after beating their head against their HPC wall:
[mariadb]
plugin_load_add = "ha_rocksdb.so.avx2"

Adding that to your my.cnf after creating the symlink will make it persist restarts.

The upstream mariadb plugin loader should probably behave the same. Maybe the file mariadb plugins should get renamed to invert the '.so'[.arch] since these aren't loaded the normal way like a normal shared lib. Then someone can plugin_load_add = "ha_rocksdb.avx2" and not need to use symlinks.

Cheers everyone!

**Comment by fenrus75** [comment]
this is both great and not; great that it works, not in that this is more
cumbersome than it should be.

I'll try to see if I can make this automatic on the mariadb side
