### ISSUE TITLE
Issues with wpa_supplicant

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/distribution#421]
- Wifi speed dropped on the latest Clear release. One possible remedy was to force CCMP (AES) in the configuration but that didn't totally resolve the problem. 
- wpa_cli didnt seem to be able to connect to the wpa_supplicant daemon either despite the fact it was running.
- wext support doesnt exist

**Comment by phmccarty** [comment]
@harsh-telepathy - Sorry for the late response. This issue was logged at the clr-bundles repo, but bugs were not being actively tracked there.

Do you happen to recall which Clear release introduced the regression? Since you filed this report on 2018-11-01, there are relatively few releases to examine for a possible root cause. Also, do you continue to experience issues with wpa_supplicant?

Here are some of the relevant release notes from the 2018-11-01 timeframe:

https://cdn.download.clearlinux.org/releases/26000/clear/RELEASENOTES-25960-to-26000
https://cdn.download.clearlinux.org/releases/26010/clear/RELEASENOTES
https://cdn.download.clearlinux.org/releases/26020/clear/RELEASENOTES
https://cdn.download.clearlinux.org/releases/26030/clear/RELEASENOTES
https://cdn.download.clearlinux.org/releases/26040/clear/RELEASENOTES

**Comment by puneetse** [comment]
@harsh-telepathy I'm closing this issue because it has been a while since it was originally reported and we haven't heard back. There have been many releases since with wpa_supplicant in use widely. Please let us know if you continue to see problems with this!
