### ISSUE TITLE
slim down gnome desktop bundle

### ISSUE THREAD

**Issue by zlnd** [clearlinux/distribution#423]
hi! is there any possibility to slim down the gnome desktop bundle? i mean, gnome apps have evolved great and are pretty useful, but many users do not need programs like cheese, or maps, to say some. by my experience **not even tracker, evolution and it's services are required for a fully functioning gnome desktop.** a barebones option can be helpful for both power users and owners of under powered, low storage machines, etc. maybe removing desktop-apps as a dependency of desktop bundle can do the trick?

**otherwise, thanks for your hard work!! really appreciating your os and waiting to see your innovations, optimizations and tweaks on other linux systems!**

**Comment by bryteise** [comment]
@eero-t At this point I don't think we have enough time to validate splitting the bundle. Work is underway to make finer grain bundles so we might get to this point eventually but this issue isn't the goal of that work and will be more of a byproduct. I'll keep this open and probably comment on it in a month or two as that work progresses.

**Comment by eero-t** [comment]
@bryteise Gnome isn't a problem for me personally (as I use just self-built Weston), but some other bundles have (at least had) very illogical content. I think worse example of this was phoronix-test-suite (year ago we needed one 200k python2 extension, and only bundle providing it was a multi-GB sized phoronix-test-suite one, instead of something related to python2).

=> any work in splitting things more logically is very much appreciated!

**Comment by fenrus75** [comment]
We are refining at a steady pace...

On python2 stuff though... that’s getting kicked out of the os at a steady
state as well with the near term upstream eol of python 2... from a
security policy perspective we need to not depend on this anymore before
that eol date

**Comment by eero-t** [comment]
I think a minimum splitting policy could be that libraries that can be used also by other applications (i.e. ones that are in standard locations), are bundled separately from the applications using them.  In the phoronix-test-suite case, they could be e.g. in a separate phoronix-test-suite-libs package, if there isn't more logical place for them.

As to Gnome, additional splitting besides libs is bit harder because there are also services and deps for those can't be detected as easily.

> We can't rely on how much Ubuntu or debian tests, so unfortunately that information is only casually useful.

Validity of that information:

Package dependencies for direct library linkage, along with library (symbol) versioning is auto-generated by DEB packaging tools, so that should always be correct.  Other dependencies are added manually to packages.  I assume same is also the case with RPMs.

Ubuntu and Debian (where Ubuntu gets its Gnome packages) have enough desktop users, that I would imagine any package dependency issues with the overall end result to surface immediately and be fixed.  While I concur there to be *much* less testing for configurations where a non-default subset of things is installed,  I would assume e.g. above listed 3 high level meta-packages to have enough coverage (I've even used them myself on some machines).

Usefulness of it:

Mapping the package names to RPM names can be anything but straightforward, so your upstream should be better example than Ubuntu/Debian (my examples were from Ubuntu because last time I've used RPM based distros was decade ago).  If your upstream RPM distro has similar Gnome meta-packages, using & testing their deps  (first on that distro) could be a good starting point.  You could even ask interested volunteers for your upstream distro meta-package testing, instead of doing it yourself.

PS. We updated all our Python scripts to support python3 last summer, so we don't anymore have a problem with python2 stuff.

**Comment by eero-t** [comment]
> I would assume e.g. above listed 3 high level meta-packages to have enough coverage

Quick comment from nearby Debian Developer; there's no policy mandating testing for meta-packages, they're just a convenience for simplifying package dependencies.

One way to gauge testing coverage, would be to look into (opt-in) package popularity-contest statistics:
* https://popcon.debian.org/
* https://popcon.ubuntu.com/

And compare its statistics to most-installed package pulling it in.  That difference tells how many installs there are that have "tested" having just the indicated (meta-)package.

Doing this showed that the difference for above 3 packages are pretty small, and (Ubuntu specific) vanilla-gnome-desktop package total install base is too small (according to popcon) to be useful  => ignore my comments about Ubuntu having reasonable testing coverage for intermediate Gnome meta-packages

**Comment by bryteise** [comment]
I would say my long term goal is to have package level bundles for everything that makes sense. I'm not interested in having subpackage level splitting (-bin, -lib style) at this time though.

**Comment by bryteise** [comment]
The desktop bundle has gone through a few rounds of also-add work and so is able to be slimmed down almost to the point of only gnome required content. I note some of the extensions and other packages can't be removed but I am going to close out this generic issue in favor of specific requests at this point.
