### ISSUE TITLE
A2DP fails with default GNOME desktop

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#54]
When using the default gnome desktop, two instances of pulseaudio end up being executed, one for gdm and the other for the active user.  This breaks bluetooth headsets from showing up as sinks.

Just attempting to killall pulseaudio will not work around the issue since both instances will immediately respawn, but you can demonstrate pulseaudio correctly working with the a2dp profile by:
* turning off your headset
* moving /usr/bin/pulseaudio to some other location
* killing both pulseaudio instances
* moving pulseaudio back
* restarting pulseaudio
* turning your headset back on

... in this scenario only the user session kicks off and audio is correctly directed to the headset

**Comment by rustylynch** [comment]
Note that I can work around this by creating a /var/lib/gdm/.config/pulse/client.conf that contains:
autospawn = no
daemon-binary = /bin/true

**Comment by mrkz** [comment]
@rustylynch yeah, apparently this is the default behavior from upstream gdm as I've seen some workaround now for [debian](https://wiki.debian.org/BluetoothUser/a2dp#Refused_to_switch_profile_to_a2dp_sink:_Not_connected) and [archlinux](https://aur.archlinux.org/packages/pulseaudio-bluetooth-a2dp-gdm-fix/).

Will check with upstream gdm folks for a proper solution. In the meantime, we can provide a workaround to avoid users doing as you mention and the things to work out of the box.

Will close once the fix is released.

**Comment by rustylynch** [comment]
After upgrading to Clear Linux version 22300, removing my workaround, and then rebooting, I can see A2DP is working as expected
