### ISSUE TITLE
Flatpak failing when bundle desktop is not installed.

### ISSUE THREAD

**Issue by Drakota** [clearlinux/distribution#619]
I installed Clear Linux* without the desktop-autostart package, because I wanted only KDE, when installing the `flatpak` bundle, I get this error when trying to add a remote: 
```
(flatpak remote-add:3369): GLib-GIO-ERROR **: 10:15:06.086: No GSettings schemas are installed on the system
```
Which does not happen when the `desktop` package is not installed, but I have the `desktop-kde` instead.

**Comment by sunnyflunk** [comment]
I was wondering why I struggled to trigger an equivalent issue via `kde-gtk-config` (turns out the schemas got compiled and remain from when I first had gnome installed for a couple of days).

`desktop-kde` won't install `glib-bin` which contains the symlink required for `10-glib-schemas-hook.sh` to run (it does have `/usr/libexec/glib-compile-schemas` though). Without it, no schemas get compiled, whether they are installed or not.

For full integration, you will also want `gsettings-desktop-schemas`, which is required to change gtk theme in the plasma settings (and needed for several gtk applications). Without it you get a crash:

`(systemsettings5:15978): GLib-GIO-ERROR **: 10:35:10.490: Settings schema 'org.gnome.desktop.interface' is not installed`

**Comment by ahkok** [comment]
This is unfortunately not so easy to resolve since we don't have many people that don't have gnome installed - maybe @anselmolsm can look into this?

**Comment by anselmolsm** [comment]
Added to my TODO list :)

**Comment by anselmolsm** [comment]
glib-bin was added to desktop-kde, released in 29030.
