### ISSUE TITLE
devpkg-boost 1.70.0 update please

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#621]
**List the package you would like to see updated**
devpkg-boost

**Does this update provide any significant new features that may be needed**
I'm building RStudio, which requires boost >= 1.69.0, while the current version in devpkg-boost is 1.68.0.

**Comment by thiagomacieira** [comment]
Thank you for your request. The problem with Boost is that it breaks binary compatibility with every release, which forces us to rebuild everything that uses it. That's why we're somewhat slow in updating, even skipping some releases.

I suppose we can squeeze this upgrade in when we upgrade to GCC 9 next month, which will require rebuilding a lot of code anyway.

**Comment by phmccarty** [comment]
I have started working on updating to boost 1.72.0

**Comment by phmccarty** [comment]
My work on updating boost was delayed again, but I spent some time the past few days working through compatibility issues for packages building with the latest boost.

That work is nearly done, so I am updating boost to 1.72.0 today. It should be available in 1-2 days.

**Comment by phmccarty** [comment]
Released in `32600`.
