### ISSUE TITLE
Unable to perform screen lock on GNOME Flashback

### ISSUE THREAD

**Issue by kahteik** [clearlinux/distribution#676]
Pressing `Win Key + L` on GNOME desktop should lock the desktop immediately. This is not the case on GNOME Flashback. Neither the combination key nor the lock screen button from the drop down menu at the top right corner could work.

Error message from `journalctl`:
gsd-media-keys[1904]: Couldn't lock screen: Cannot invoke method; proxy is for the well-known name org.gnome.ScreenSaver without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

Clear Linux version: 29250

**Comment by mrkz** [comment]
from the journal I get:
```
May 07 13:14:10 clr-vm gnome-panel[1240]: Could not ask screensaver to lock: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.ScreenSaver was not provided by any .service files
```

so likely missing files for the fallback session.
```

**Comment by mrkz** [comment]
Turns out, `gnome-flashback` session depends on `gnome-screensaver` program (which  is inactive/archived project fwiw).

I added `gnome-screensaver` to CLR, but I also [created a bug in the gnome-flashback project](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/18) to follow-up and see what's next for the project depending on not-actively-maintained software.

Hopefully the fix will be available in release **29890** (or later)
