### ISSUE TITLE
Changing CPU governor doesn't work on a Xeon E3-1241 v3

### ISSUE THREAD

**Issue by mariojuniorjp** [clearlinux/distribution#683]
**Describe the bug**
When a try to change CPU governor, I receive an error message: "bash: /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor: ambiguous redirect"

**To Reproduce**
1. Open terminal and type: echo powersave > /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

**Expected behavior**
Expected is the change of the governor

Clear Linux OS version: [cat /usr/lib/os-release]
AME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"

**Comment by mrkz** [comment]
Hello,

I'm not sure if the redirection operator (`>`) would allow you to perform the way you're trying to. I say so because using the wildcard (`*`) on the path you're mentioning, would expand the command as follows (my example run on a 8-cores CPU):
```
$ echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
```

The previous expression is invalid for the redirect (`>`) operator, hence the error you're facing.

Probably using a for loop would do the trick:
```shell
for core in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do; echo powersave > $core ; done
```

I'm closing the issue now, should you experience more issues, please do not hesitate to open a new issue.

**Comment by thiagomacieira** [comment]
Aternative: 
```sh
echo powersave | tee sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```
Or by using HERE=word:
```sh
tee sys/devices/system/cpu/cpu*/cpufreq/scaling_governor <<<powersave
```
