### ISSUE TITLE
Dropbox and Chrome/Chromium support

### ISSUE THREAD

**Issue by m-parashar** [clearlinux/distribution#71]
Hi there. I deeply appreciate your work on this Linux distribution. Fast and efficient. Best GNOME experience on three laptops I have installed it on. Yes, bare metal.

Having Dropbox and Google Chrome/Chromium in the repos would be wonderful. I would suggest VS Code too, but there is a Flatpak available, so it's not a priority.

**Comment by tomByrer** [comment]
> Google apps might be limited due to licensing issues

Chromium is OSS, project; there are many forks of it.  I'd hope of build specific for Clear would take advantage of the optimizations.

**Comment by fenrus75** [comment]
Chromium in some form we should be able to do; question is just one of time
and priorities

**Comment by bwarden** [comment]
Dropbox was rejected due to licensing, but I'm successfully using the flatpak release.

**Comment by OpenSourceAnarchist** [comment]
Any news on Chromium/Chrome bundle? Chromium is available as Flatpak and Chrome can be installed on Clear Linux using `sudo rpm -Uvh --force --nodeps path/to/the/rpm`, but native availability with Clear's optimizations (if applicable) would of course be preferred.

**Comment by OpenSourceAnarchist** [comment]
This is a bit of a "bump" on this issue.

Is it possible to provide a pundle that acts as a script that downloads the official Chrome rpm binary? Like how Firefox is handled? That way Intel is NOT redistributing the Chrome binary, since it is merely a script that runs on the user's computer, and users do not have to fiddle with manual installations of rpms?

I'm not familiar with IP law, but I can't see how this could violate anything, since users are the ones downloading the binary. The rest of the pundle could make Chrome install nicely, like the Firefox pundle, so that it can be auto-updated through swupd with changes to the url and a revision bump.

**Comment by ahkok** [comment]
With firefox nothing is downloaded. We can currently not do this for Chrome.

**Comment by ahkok** [comment]
Closing this for now. We have 8 bugs asking for chrome or chromium, and this one is ambiguous. Please track #422 or one of the other ones.
