### ISSUE TITLE
Partitions order/geometry error in clear-29400-live-desktop.iso ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#736]
Trying to put the live desktop iso on USB stick bigger than 2.4GB (??!!), I faced issues to reuse the remaining of the space.
Eg: impossible to create a vfat partition and use it

When dumping the image layout I see :
>$ sudo fdisk clear-29400-live-desktop.iso
>
>Welcome to fdisk (util-linux 2.33.1).
>Changes will remain in memory only, until you decide to write them.
>Be careful before using the write command.
>
>Command (m for help): p
>Disk clear-29400-live-desktop.iso: 2,2 GiB, 2389770240 bytes, 4667520 sectors
>Units: sectors of 1 * 512 = 512 bytes
>Sector size (logical/physical): 512 bytes / 512 bytes
>I/O size (minimum/optimal): 512 bytes / 512 bytes
>Disklabel type: dos
>Disk identifier: 0x430a5a69
>
>Device                        Boot Start     End Sectors  Size Id Type
>clear-29400-live-desktop.iso1 *        0 4667519 4667520  2,2G  0 Empty
>clear-29400-live-desktop.iso2        136  204935  204800  100M ef EFI (FAT-12/16/32)

=> I think this order/geometry is incorrect : first partition (1) begins at 0 and end at 4667519,
while the second (2) begins and ends within the first one at 136 / 204935 (??!!)

By comparison, and old CLR Installer image on another USB stick had this correct layout :
>$ sudo fdisk /dev/sdb
>
>Welcome to fdisk (util-linux 2.33.1).
>Changes will remain in memory only, until you decide to write them.
>Be careful before using the write command.
>
>Command (m for help): p
>Disk /dev/sdb: 7,3 GiB, 7864320000 bytes, 15360000 sectors
>Disk model: STORE N GO      
>Units: sectors of 1 * 512 = 512 bytes
>Sector size (logical/physical): 512 bytes / 512 bytes
>I/O size (minimum/optimal): 512 bytes / 512 bytes
>Disklabel type: gpt
>Disk identifier: E93F536A-8285-4B40-82B3-A3DDF00F3347
>
>Device      Start     End Sectors  Size Type
>/dev/sdb1    2048  292863  290816  142M EFI System
>/dev/sdb2  292864  792575  499712  244M Linux swap
>/dev/sdb3  792576 5992447 5199872  2,5G Linux root (x86-64)

**Comment by mdhorn** [comment]
@evil-brian Can you review this. I don't think what they want to do with the ISO image is possible; we had a similar discussion previously with @bktan8

**Comment by mdhorn** [comment]
@ahkok Can you please add @evil-brian to the 'distribution' membership and transfer this issue to clr-installer?

**Comment by nsauzede** [comment]
@mdhorn if you forget what I what trying to perfom at first (ie: reuse extra space beyond the theoretical 8GB occupied by the ISO contents), my guess about the invalid ISO partitions geometry still stands :
is it expected to have partitiions inside partitions ?
The problem I see is that when you "burn" this ISO on an USB stick, and put it eg: on a windows/linux host, the disk manager of the OS can be confused by this strange layout

**Comment by nsauzede** [comment]
Or am I missing some magic, and in case you burn this ISO on an USB stick larger than 8GB (eg: 16GB)
then the rootfs of the live image is expanded to 16GB, and thus can already be re-used as is ?
(in my first comment, I mentioned 2.4GB because this is the actual ISO file size, but I just realize that the rootfs is kind of compressed, and supposed to occupy really 8GB on the stick ? or ??)

**Comment by evil-brain** [comment]
The ISO image provided utilizes a hybrid partition layout - I use the `gdisk` application to read these.
It has both an MBR and GPT, so we can support booting on Legacy BIOS and uEFI.

You cannot resize the image easily, but it may be possible, and there's some thoughts below.


Here's the output for both GPT and MBR partitions on the ISO (first GPT, then MBR):
```
# gdisk dev-clear-live-server.iso 
GPT fdisk (gdisk) version 1.0.4

NOTE: Write test failed with error number 13. It will be impossible to save
changes to this disk's partition table!

Partition table scan:
  MBR: MBR only
  BSD: not present
  APM: not present
  GPT: present

Found valid MBR and GPT. Which do you want to use?
 1 - MBR
 2 - GPT
 3 - Create blank GPT

Your answer: 2
Using GPT and creating fresh protective MBR.
Warning! Main partition table overlaps the first partition by 64 blocks!
You will need to delete this partition or resize it in another utility.

Command (? for help): p
Disk dev-clear-live-server.iso: 1138688 sectors, 556.0 MiB
Sector size (logical): 512 bytes
Disk identifier (GUID): E773E3B7-C66C-4C8E-902D-B897DAFB145A
Partition table holds up to 248 entries
Main partition table begins at sector 2 and ends at sector 63
First usable sector is 64, last usable sector is 1138624
Partitions will be aligned on 8-sector boundaries
Total free space is 1 sectors (512 bytes)

Number  Start (sector)    End (sector)  Size       Code  Name
   2             136          204935   100.0 MiB   0700  ISOHybrid1

Command (? for help): r

Recovery/transformation command (? for help): o

Disk size is 1138688 sectors (556.0 MiB)
MBR disk identifier: 0x00000000
MBR partitions:

Number  Boot  Start Sector   End Sector   Status      Code
   1                     1      1138687   primary     0xEE

Recovery/transformation command (? for help): 
```

and fdisk:
```
# fdisk -l dev-clear-live-server.iso
Disk dev-clear-live-server.iso: 556 MiB, 583008256 bytes, 1138688 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4b9a62e8


Device                     Boot Start     End Sectors  Size Id Type
dev-clear-live-server.iso1 *        0 1138687 1138688  556M  0 Empty
dev-clear-live-server.iso2        136  204935  204800  100M ef EFI (FAT-12/16/32)
```

> => I think this order/geometry is incorrect : first partition (1) begins at 0 and end at 4667519,
> while the second (2) begins and ends within the first one at 136 / 204935 (??!!)

This struck me as odd as well, I can't seem to find _why_ this is exactly in the documentation.

From the[ Debian wiki](https://wiki.debian.org/RepackBootableISO) linked below, they also use 'fdisk' on an ISO image. I *think* that fidisk by default prints out both MBR and GPT information, and since they overlap, it's confusing.

The man page doesn't explain this behavior and my internet searching doesn't show any documentation on this functionality. I concluded fdisk probably prints both tables from the above output from gdisk and fdisk. The only thing that doesn't jive is the larger partition is shifted by one sector (starts on both 0 and 1, depending on which program you use), but is the same size when comparing outputs.

So, to use the extra space on the USB stick you may be able to use the method in the Debian wiki and resize the rootfs. You can also do what the 'rufus' program on Windows does - build a new USB stick, set up isolinux on it, and then copy all files over from the ISO. I'm currently investigating a program which does this on Linux.

More information below:
When the ISO is built we use xorriso and a couple standard isohybrid flags:
```
		"xorriso", "-as", "mkisofs",
		"-o", imgName + ".iso",
		"-V", "CLR_ISO",
		"-isohybrid-mbr", tmpPaths[clrCdroot] + "/isolinux/isohdpfx.bin",
		"-c", "isolinux/boot.cat", "-b", "isolinux/isolinux.bin",
		"-no-emul-boot", "-boot-load-size", "4", "-boot-info-table",
		"-eltorito-alt-boot", "-e", "EFI/efiboot.img", "-no-emul-boot",
		"-isohybrid-gpt-basdat", tmpPaths[clrCdroot],
```
According to https://wiki.debian.org/RepackBootableISO , the -isohybrid-mbr flag 'Installs an MBR at the start of the ISO image. This enables booting from USB stick via legacy BIOS.' , and  -isohybrid-gpt-basdat  flag 'causes the creation of a partition of type 0xef in the MBR partition table. It also causes production of a GPT which stays invalid, nevertheless, because of the existence of the MBR partition.'

Fdisk's second entry is 100MB which is the size of our EFI boot partition filesystem added by the '-isohybrid-mbr' flag. 

file is another utility that provides some input:
``` dev-clear-live-server.iso: DOS/MBR boot sector; partition 2 : ID=0xef, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 136, 204800 sectors ```
So, It seems that the second entry (starting @ sector 136) is definitely the 100MB EFI partition.

Some info on isohybrid filesystems: https://wiki.syslinux.org/wiki/index.php?title=Isohybrid
Lots of deep info here: https://www.rodsbooks.com/gdisk/hybrid.html

**Comment by nsauzede** [comment]
wow thanks for this detailed feedback
concerning the off-by-one for first sector, I think to remember it's rather a convention delta : some documentation state that first sector is 1 (rather legacy docs, circa msdos etc ?) and others would just number it 0 -- but I might be wrong here..
It's a good thing if someone is investigating the current hybrid ClearLinux ISO layout, possibly trying to improve/clean it and/or allow resizing/reusing the "remaining part" of bigger USB drives
I guess I'm not the only CLR user frustated by burning eg: a 16GB USB drive with an 2.3GB ISO file, obtaining a funky partitions layout, and not being able to reuse the "lost" parts.. :-)

**Comment by mdhorn** [comment]
@nsauzede The installer image intentionally sized with a trade-off of content available for use in the live image versus the minimum required size of the USB. We settled on an 8GB USB as the target; which means we have to drop that down to fit manufacture usage and variations, so around 7.8GB.

The live image is read-only, so each time you reboot anything which was configured will be lost.
The use case is to explore and test out Clear Linux* OS without the need to install first, and then enable the installation onto permanent media.

Can you please elaborate on what use case you're trying to enable to we might better understand if there is something we can consider changing?

**Comment by nsauzede** [comment]
Now that I have been provided more context about the hybrid mode, and the target of the live-image to be pure RAM-based, I recognize there is little gain to either "fix" the funky layout and/or reuse the surplus space beyond the actual live-image compressed contents (like 2.4GB ?)
I guess I can close the issue now
