### ISSUE TITLE
Support Sierra EM7455 LTE card

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#78]
The Sierra EM7455 LTE is a common LTE card for Dell, Lenovo, and other laptops.

I have one in my Thinkpad 470s.

It is supported in kernel 4.7+ and by ModemManager.

However it does not appear in gnome after installing gnome-autostart.

Here is hardware information:

https://gist.github.com/sirredbeard/ac61ca6c762535736599dd0b08b2423c

**Comment by fenrus75** [comment]
your logs show this is an "mbim" class modem; which we only had partially enabled

fixing now

**Comment by bryteise** [comment]
@sirredbeard Is this working for you now?

**Comment by sirredbeard** [comment]
Unfortunately it is not.

I am on 23110, but do not see my WLAN connection in Gnome Shell or Gnome Control Panel:

![screenshot from 2018-06-18 21-15-33](https://user-images.githubusercontent.com/33820650/41563205-8376cd7e-733e-11e8-880e-aeaf9a135a0a.png)

Diagnostic data:

https://gist.github.com/sirredbeard/e6940b5ee00b14f84cc2d6dfc9564a5d

Let me know what you need from me to debug.

**Comment by bryteise** [comment]
Hrm does it start showing up if you modprobe cdc_mbim?

**Comment by sirredbeard** [comment]
Sadly, no.

iconfig
https://gist.github.com/sirredbeard/db0135d7e0fe090fcb79359259768143

lsmod after your recommended command
https://gist.github.com/sirredbeard/f496c7c4ffb6ad1250f8baad6f9d421d

**Comment by bryteise** [comment]
Ah so I think I found the issue, modemmanager is only in the desktop-dev bundle. Could you try and install that bundle (and maybe restart) and see if it starts working? I'll be adding it to the main desktop though.

**Comment by hunger** [comment]
I have such a modem to and am currently at 23290 with the 4.17.3 kernel that came with.
`/usr/bin/ModemManager` is available, the `cdc_mbim` module is loaded.
`nmcli r` shows WWAN-HW as enabled and WWAN as enabled.
Gnome does not show anything about the modem in the top-right menu.

`nm-connection-editor` let's me launch a wizard for a new Mobile broadband connection, but the process fails since there is no provider information available (and I do not know the details myself;-).

The upstream URL for that data is: https://gitlab.gnome.org/GNOME/mobile-broadband-provider-info.
Copying the files from Arch Linux into clearlinux improves the situation somewhat and adds all the necessary information to the wizard. I got my connection now!

But that does not allow me to connect to that connection:-/

When I do `nmcli` I get the following output:
`wwp0s20f0u2: unmanaged
    "Sierra Wireless EM7345 4G LTE
    wwan (cdc_mbim), FF:FF:FF:FF:FF:FF, plugin missing, hw, mtu 1428`

So there seems to be a plugin missing: /usr/lib/NetworkManager is surprisingly empty... I do have libnm-device-plugin-wwan.so there in other distributions (provided by the NetworkManager package).

**Comment by bryteise** [comment]
Hrm looking at our networkmanager package I definitely see this as being disabled. Paging @AthenasJimenez @mrkz for packaging changes here.

**Comment by AthenasJimenez** [comment]
I made some changes on NetworkManager.spec adding new flags and removing the duplicated :P  You would see the changes on the next release. 

Regarding to libnm-device-plugin-wwan.so and the rest of the libraries, you may find it on /usr/lib64/NetworkManager :)

**Comment by hunger** [comment]
Thanks! I'll try to test that over the weekend!
And yes, I do feel a bit stupid for missing /usr/lib64/NetworkManager! :-)

**Comment by hunger** [comment]
There probably was progress: It seems like some ModemManager-related code is now showing up in gnome-shell. Please see #111 for details.

I was unable to test due to that issues:-(

**Comment by hunger** [comment]
#111 is fixed in 23450, but the modem still does not work.

The kernel modules are loaded.

ModemManager is active and org.freedesktoo.ModemManager1 is visible on the system bus and d-feet lists it as "activatable".

Trying to interact with that service raises an DBus exception (AccessDenied).

Trying the "reload" button freezes d-feet for about one minute.

This is the only service on the system bus that I can not I trospect, so this seems very fishy.

**Comment by hunger** [comment]
`nmcli r` lists WWAN as enabled.
`nmcli d` does *not* list the modem, just loopback, wifi and ethernet.
Straight `nmcli` does not mention anything about Sierra anymore.

**Comment by hunger** [comment]
The journal contains no smoking gun AFAICT:

There are several lines about d-feet being rejected by now:
```dbus-daemon[521]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.420" (uid=1000 pid=3325 comm="/usr/bin/python /app/bin/d-feet ") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.freedesktop.ModemManager1" (bus)```

Apart from that I get several lines about Modem manager not being able to get its bus name... I guess that is due to systemd pre-registering that? I did try to run ModemManager a couple of times manually with the debug flag to find out more, but that also failed due to the bus name being taken already.
I did try to mask the service file and reboot, but still the name is taken:-/

**Comment by hunger** [comment]
No change in 23510.

**Comment by tpleavitt** [comment]
Close for now.  If reoccurs please reopen
