### ISSUE TITLE
kernel-native: enable suspend/resume/idle debug tooling by turning on kprobes, function_tracer

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#863]
Propose we turn the following kernel features on in (at least) kernel-native:
- ~~FTRACE~~
- FUNCTION_TRACER
- KPROBES
- ~~DEVMEM (strict)~~

**Comment by thac0** [comment]
Colleagues: please assign this to me ( @thac0 ). Thanks!

**Comment by miguelinux** [comment]
CL is following security rules from
https://github.com/clearlinux-pkgs/kernel-config/blob/master/mandatory-5.1

There you will see that:

- [ ] DEVMEM (strict) `MUST_BE_UNSET["CONFIG_DEVMEM"] = "/dev/mem is dangerous and has no legitimate users anymore"`, is not allowed
- [x] FTRACE is already enabled.
- [ ] FUNCTION_TRACER is not enabled.
- [ ] KPROBES  is not enabled

**Comment by thac0** [comment]
@miguelinux Roger that. I'll not push for DEVMEM. I'll submit a patch soon enabling the others.

**Comment by thac0** [comment]
Shall I enable function_tracer and kprobes in the 'linux' package config-fragment (and regenerate the config), or enable them in kernel-config package's base-5.1? @bwarden @miguelinux

**Comment by bryteise** [comment]
So I know kprobes impact on boot time is limited I'm worried we are going to be moving towards a death by 1000 cuts with a few ms here and there for enough changes. Can debug kernels be built by those doing the debugging instead of turning these on all the time?

**Comment by thac0** [comment]
I see them as vital components of a developer's tool belt-- especially a kernel developer's. These are useful features to have at your disposal, especially when doing feature enabling and evaluation. That said, I appreciate the tension with respect to performance.

At the risk of going off into the weeds... Broken down, I get this "host versus target" vibe in situations like this. Clear as the "Host": the daily software development environment, with all the facilities and tools necessary to be productive. And Clear as the "Target": the heavily optimized, highly tuned for a specific usage model, not necessarily optimized for daily development work. Not sure what to do with those thoughts at the moment, but there they are.

**Comment by bryteise** [comment]
I agree they are very useful for a kernel developer. For a system being developed I often find that these systems are not my daily usage system but one that has the hardware I'm working on and might have a different kernel at that point anyway. My daily system I use for to develop *on* tends to be pretty streamlined and I have other hardware/vms for doing development *in*.

I guess I would say this is likely down to an individual workflow and there is a tension between them. Having a dev oriented kernel is likely not a bad idea but it may be rather than making a new kernel as such it might be easier to streamline a workflow to enable customizing the Clear Linux kernel being worked on and have those changes persist across updates.

**Comment by thac0** [comment]
Hmm. A local config fragment perhaps, a file not tracked by Clear's package repo? Broken down: given linux package Makefile checks for the existence of 'config-local-fragment' file, and if it's there, merges it in at build time? As it stands, my workflow entails carrying a config-fragment patch around along with a 'make config && make build' stanza.

**Comment by bryteise** [comment]
I think it probably needs a few things. Create a custom hook via a system configured update-triggers.target.wants that will run the tooling, tooling to build the kernel with the config fragment and install it in the sysadmin path for custom kernels and instructions for setting up a kernel workspace with the config fragment format and configuration so that the tool finds this workspace.

**Comment by ms178** [comment]
"Instead though I would prefer, rather than making a new kernel, to create a workflow that enables customizing the Clear Linux kernel and have those changes persist across updates." Just my two cents from the peanut gallery: As a power user, I am really lookig forward for such a feature. A seamless and easy process to get there is one reason I come back to openSUSE Tumbleweed, because I can use the "make rpm-pkg" target from the mainline kernel and adjust the config and the Makefiles with my own flags relatively easily (this is a pain on other Distros which don't use rpm or deb packages). Thus I get an installable package which is registered in the package manager. Also, Zypper (Suse's package tool) asks before each update if I want to keep my custom kernel. This process could be even more automated / simplified. I can think of a GUI where I can enter my custom CFLAGS/CXXFLAGS/LDFLAGS and select all Kernel settings which hides all of the manual handling of these files from the user.

**Comment by bryteise** [comment]
If you want to introduce this first as a more manual process, adding Makefile targets for the kernel packages seems pretty straightforward and something that could be done with a quick turn around.

**Comment by ms178** [comment]
Having a nice and easy way to build other performance sensitive packages (like e.g. Mesa) with custom flags would be also great.

**Comment by miguelinux** [comment]
@ms178  are saying you want to build the kernel outside  **CL common tooling** (outside mock)?

**Comment by ms178** [comment]
@miguelinux As I just spent a very brief amount with Clear Linux last time on borrowed hardware, I wasn't able to have a look on your common tooling, but from a first glance, that could be one way of achieving what I had in mind. It depends on how flexible your tooling is and how seamless and fast it works in practice though. It sounds familiar to Solbuild on Solus where I had noticed a couble of usability flaws (but the the general idea was great!). I would need more time to test it out though to provide any valuable feedback. Once I get the chance, I'll let you know (could take some time though).

My current way of doing things on Tumbleweed is - albeit including many manual steps - pretty easy to setup and maintain once one knows what to do. At least for the Linux kernel (not for anything else). Other distros which I had tried fail hard in this regard because the whole process to get a package compiled from sources with custom compiler flags is just too hard to setup or doesn't work at all in the end (e.g. the "modern way" on Manjaro).

**Comment by bryteise** [comment]
> Having a nice and easy way to build other performance sensitive packages (like e.g. Mesa) with custom flags would be also great.

I doubt we'd support this kind of thing outside of kernels as replacing distro components isn't something we want to get into. Kernels are nice because of how they are self contained components that we already have support for user's using their own versions.

**Comment by ms178** [comment]
> I doubt we'd support this kind of thing outside of kernels as replacing distro components isn't something we want to get into. Kernels are nice because of how they are self contained components that we already have support for user's using their own versions.

Other performance sensitive packages might be self-contained as well and provide some real benefits (a even more optimized build of GCC comes to my mind). If the users mess up their system, it is their responsibility and having such a tool would be great. But I understand that this introduces hard to support scenarios and after all: Clear Linux is not Gentoo.

**Comment by thac0** [comment]
After talking with @fenrus75 , I'm going to let this one go.

My original intent was to enable additional tooling for suspend, resume, and idle (pm-graph, to put a fine point on it). However, I'm now scrutinizing why and how the *tooling* gathers its data in these particular ways.

So, for now, going to shift focus to the tooling, as opposed to pushing Clear to turn on kprobes and related facilities.
