### ISSUE TITLE
RTL8821ce not working

### ISSUE THREAD

**Issue by Feyisayo** [clearlinux/distribution#869]
Hello there,
I am trying out clearlinux on an HP pavilion having previously ran Ubuntu 19.04 on it. 

The laptop has an RTL8821ce wifi card but I cannot get the wifi card to work.

I have installed what I think are the necessary bundles:
- linux-firmware-wifi
- hardware-wifi

Any ideas on how to get the wifi working?

**Comment by CaptSilver** [comment]
I just made a request to include this driver, ;)
You need to down and compile this: https://github.com/aircrack-ng/rtl8812au
You will also have to install dkms and disable the signature verification for the kernel modules.

**Comment by Feyisayo** [comment]
Thanks for the information. I will have a look at this repository

**Comment by Feyisayo** [comment]
I successfully installed this but the wifi still did not work

**Comment by CaptSilver** [comment]
Try: sudo swupd bundle-add kernel-native-dkms
This will disable signature verficiation and allow you to add the source code for dkms compilation. Then you can try:" sudo lsmod" and check for a RTL driver to see if its loading.

**Comment by puneetse** [comment]
I'm closing this issue for now since the drivers/firmware source are not upstream in the Linux kernel. They can be manually obtained from other places and we offer the necessary parts to use them as conveniently as possible. See https://docs.01.org/clearlinux/latest/guides/index.html#kernel

If this situation changes, please let us know!
