### ISSUE TITLE
Unable to install Flatpak applications via Software after clean installation

### ISSUE THREAD

**Issue by Mountainerd** [clearlinux/distribution#901]
**Clear Linux Version**: 29940

**Steps to Reproduce**
1. Install Clear Linux.
2. Login to clean installation.
3. Open Software and attempt to install Flatpak application. 

**Troubleshooting Conducted**:
1. Install application via Flatpak on command line (_success_)
2. Checked journalctl for any obvious Flatpak errors (_none_)
3. Removed ~/.cache/gnome-software (_success, no change to behavior_)
4. Searched for existing bug reports (_unsuccessful, none found_)

**Additional Detail**
I installed Clear using the 29930 installer. The installation was uneventful, though, during install and after, my time would only be displayed in UTC. I was able to resolve that but now I have an issue where if I open Software and attempt to install any Flatpak application, it will display **Pending installation...** and do nothing. If I drop to Terminal and install it via Flatpak command line, it installs fine. Also, while installing via command line is fine, Software shows it as an "update" on the installed tab. When I scroll to the app I installed command line Flatpak, the button doesn't say **Uninstall** -- it says **Install** and then when I click it, it asks if I want to remove the application.

**Comment by mrkz** [comment]
Apparently we got hit when updating to `flatpak-1.4.0` (see [flatpak/issues/2957 - libflatpak broke ABI in 1.4.0 which makes gnome-software explode](https://github.com/flatpak/flatpak/issues/2957)).

After I tried 1.4.1 I could install apps from flathub correctly. Already pushed the update (`flatpak-1.4.1`), hopefully this should be landing in release **30020** (or later).

Will close once the update and the fix is available.

In the meantime you could workaround this issue by installing the software directly via terminal (i.e: see application page on Flathub and look at command line instructions at the bottom)

**Comment by Mountainerd** [comment]
Just pulled down 30020 and `flatpak` was updated to `flatpak-1.4.1`. I was immediately able to install applications again from GNOME Software. Thank you @mrkz for the quick turnaround on this!
