### ISSUE TITLE
[Package request] Separating `libdbusmenu-gtk` from `uget` bundle

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#919]
`libdbusmenu-gtk3` is currently included in `uget` bundle. Although `uget` is only 2MB, it still makes sense to have a separate bundle `libdbusmenu-gtk3`.

For comparison, `libdbusmenu-qt` is included in many bundles such as `os-clr-on-clr-dev` and `desktop-dev`. I think it makes sense to include `libdbusmenu-gtk` in `desktop-dev` bundle.

**Comment by bryteise** [comment]
The *-dev bundles are autogenerated so ```libdbusmenu-gtk``` would need to be pulled in by something in desktop for that to happen. Since ```uget``` requires ```libdbusmenu-gtk3``` and I couldn't find what other bundles need it I don't think splitting out ```libdbusmenu-gtk3``` is all that useful. The reason libdbusmenu-qt is included in the other bundles you specified is that it is part of the build chain for those bundles. Is this more of a request for a devpkg bundle?

**Comment by lebensterben** [comment]
>The *-dev bundles are autogenerated so ```libdbusmenu-gtk``` would need to be pulled in by something in desktop for that to happen. Since ```uget``` requires ```libdbusmenu-gtk3``` and I couldn't find what other bundles need it I don't think splitting out ```libdbusmenu-gtk3``` is all that useful. The reason libdbusmenu-qt is included in the other bundles you specified is that it is part of the build chain for those bundles. Is this more of a request for a devpkg bundle?

@bryteise Yep, I guess it's more of a devpkg request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lebensterben** [comment]
I'm closing this since `libdbusmenu-gtk3` is in either `desktop-dev` or `desktop-gnomelibs` bundles.
