### ISSUE TITLE
Live desktop iso will hang on boot from usb, on some hardware

### ISSUE THREAD

**Issue by akamarvin** [clearlinux/distribution#930]
My main rig is Core i5-4670 Haswell , Asrock Z87M Extreme 4 (Bios 1.60 , UEFI) 16Gb
A still very decent 6yo Intel machine with dual 2560*1440 monitors (hence I don't even try VMs, because VBox limited graphical adapter handles such real estate with very poor performance)

I tried with ver. 29930 and a former one (29560 I think), 
Both with Rufus or Etcher to write the image. I also double checked the md5.

Whatever it's always the same: It starts to boot then hangs on some early firmware/kernel load with : 
`[Firmware Bug]: TSC_DEADLINE disabled due to Errata; please update ...` (cannot read the rest)

The machine is completely locked, no usual key combination can unfreeze it, and it needs a hard reset with a long push on the power button to stop it. 

The usb live image is working fine on my Asus laptop, but I want to keep a Windows on that machine with a touchscreen and a quirky resolution (3200*1800) requiring flexible HiDPI scaling. 

Any clue much appreciated. Thanks in advance.

**Comment by lebensterben** [comment]
What was the last time you update your bios?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miguelinux** [comment]
That message is old and usually is fixed in new firmware BIOS/UEFI, please update your firmware.

Are you using Nvidia Gfx card?

Try to add `nomodeset`to the kernel command line.
1. Hit down arrow key when booting, (it will bring the sd-boot menu, if it is not showed).
2. Hit `E` key to edit entry
3. Add `nomodeset` to the cmdline
4. Hit `Enter` key

**Comment by akamarvin** [comment]
The answer was in the boot sequence options in the bios 
Once the usb stick was in , there were 2 options in the boot sequence:
-- usb sansdisk usb
-- **uefi sandisk usb**

Prioritizing the second option did the job, I could properly boot the iso.

**One thing important to notice:**  the initial menu with the 5 seconds timer, is looking much different when you try to boot the USB from one method or the other.  
With the failing method, the menu has no apparent other option and is framed with a blue background. when it fails , the whole log has a greenish background to it.
With the successful method, the menu has 2 options, and is a blank light grey on black with no frame around, just highlighting of the current option.

You might want to document that.

Still, I gotta say, it's a first, I never had to meddle with the bios for any other distro I've ever installed or tried. And I tried a lot, I'm of the hopper kind, Fedora 30 and openMandriva lx4 lately . 
Even if I stuck with Mint for 1 year, then Manjaro for 2 years, then had to go back to windows to facilitate interactions with Office365, VStudio and Azure, for work.

The problem here might have something to do with the dogmatic and weird way you load the microcode updates (late) (see #52)

You should not require that kind of meddling from end users. A live iso should not require a specific bios setting. Never ever. It should go smoothly, whatever the type of usb boot.

Clearlinux is noticeably promising, in terms of perceived speed , performance, footprint.
And i'm still curious about giving it its full power with an install on a spare SSD. But I do wonder about a grub mulitboot, for instance, with the kind of initialization you have chosen.

**Comment by lebensterben** [comment]
>The answer was in the boot sequence options in the bios  ...

@akamarvin Some motherboards have a compatibility mode when it's booting from USB device, external PCI device, and external network location. 

That is to say, your main OS will identify it as in UEFI mode instead of BIOS, but when you boot from other devices they may appear differently from what you expect.

It's likely that your motherboard has this compatibility function and offers your two entries, in BIOS and UEFI mode respectively, in the boot menu.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrkz** [comment]
@akamarvin Hello, first of all, thanks for reaching out and openning this issue :tada: !

I have created an issue into our documentation repository (as noted in the previous link reference by GitHub) so we make this easier to grasp when following the installation guide.

I'm closing now this issue (as I understood that your issue is now solved).

Otherwise, please open a new issue with details about the issue you're facing.

Again, **thanks for your feedback** :tada:
